### ISSUE TITLE
Outdated examples in orbit_plot module documentation

### ISSUE THREAD

**Issue by Badidzetai** [esa/pykep#105]
### What's wrong 
Sphinx autogen documentation of the esa.github.io web interface uses the docstrings of python functions to write the doc page. Examples in several docstring of the module orbit_plotting are outdated or straight buggy. Git blame shows they were written in 2015, they just need a bit of refreshment.

env and version : conda binaries for windows, pykep ver 2.3

### Resolution
I forked, will write working examples and do a PR in the next days

**Comment by darioizzo** [comment]
You are absolutely right ... your PR is welcomed, I am currently also refreshing the code and docs in my fork, in particular introducing nbsphinx and other small improvements ...

**Comment by darioizzo** [comment]
Maybe you could start from there to avoid possible conflicts. I plan a 2.4 release in October.

**Comment by Badidzetai** [comment]
OK will work from your fork then
