### ISSUE TITLE
No feasible solution

### ISSUE THREAD

**Issue by vascoamaralgrilo** [esa/pykep#111]
Good evening,

I am a student from Instituto Superior Técnico, Lisbon. I am using pykep and pygmo, namely the module lt_margo, in order to optimise a continuous-thrust trajectory (in the context of a project from a Masters course). However, when I run the example 11 with the algorithm compass search (for max_fevals=100), I cannot find any feasible solution. I would be grateful if someone could provide insight into this issue.

Kind regards,

Vasco Grilo

**Comment by darioizzo** [comment]
Please use our gitter channel to ask questions on the code usage (https://gitter.im/esa/pykep).

I already answered your question via mail, but in case I will repeat also here the answer: compass search cannot solve a NLP problem such as margo. In the pykep example snopt7 is indicated, but any other NLP solver would also do.

I suggest you to use snopt7.

**Comment by vascoamaralgrilo** [comment]
Thank you very much for the reply, I will try with snopt7.Kind regards,Vasco Sent from Mail for Windows 10 From: Dario IzzoSent: 03 December 2019 13:28To: esa/pykepCc: vascoamaralgrilo; AuthorSubject: Re: [esa/pykep] No feasible solution (#111) Please use our gitter channel to ask questions on the code usage (https://gitter.im/esa/pykep).I already answered your question via mail, but in case I will repeat also here the answer: compass search cannot solve a NLP problem such as margo. In the pykep example snopt7 is indicated, but any other NLP solver would also do.I suggest you to use snopt7.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
