### ISSUE TITLE
Modelling a continuous thrust transfer without non-linear constraints

### ISSUE THREAD

**Issue by vascoamaralgrilo** [esa/pykep#113]
Good afternoon,

I have been trying to use the class lt_margo to model a continuous thrust transfer. From the answer to my previous issue, the optimisation algorithms should be able to deal with non-linear constraints for that class.

On the other hand, I have researched that evolutionary algorithms are adequate for the optimisation of continuous thrust transfers, but, from the errors I got, I believe these are not suitable to problems with non-linear constraints. In order to use, for example, Hemoglop (DE + PSO + SGA) to optimise a continuous thrust transfer, I believe a class with non-linear constraints should be used to model the problem. Could the classes direct_pl2pl, indirect_pt2pt or indirect_or2or be used to model a continuous thrust transfer without non-linear constraints? If so, which one is more adequate? 

Kind regards,

Vasco

**Comment by darioizzo** [comment]
closing this as its not an issue, rather a usage question (appropriate for the gitter channel)
