### ISSUE TITLE
Issue at "make -j2 install" (MacOS)

### ISSUE THREAD

**Issue by rohanpatel747** [esa/pykep#115]
I have been trying to install Pykep for the last two days now without success. Hopefully, someone can help me out.
I began my latest attempt by using brew to install: python, cmake, boost, and boost-python. I then cloned the git directory, and began compiling the keplarian library using cmake. This ran fine, I was able to install using `sudo make install`, and all the test cases passed. I then created the "build_pykep" directory in the /pykep folder, cd'd into this dir., and ran a modified version of the command listed in the install guide for cmake: 
```
cmake -DBoost_NO_BOOST_CMAKE=ON \
      -DPYKEP_BUILD_KEP_TOOLBOX=no \
      -DPYKEP_BUILD_PYKEP=yes \
      -DPYKEP_BUILD_TESTS=no \
      -DCMAKE_BUILD_TYPE=Release \
      -DBoost_PYTHON${PYTHON_VERSION}_LIBRARY_RELEASE=/usr/local/lib/${BOOST_PYTHON_LIBRARY_NAME} \
      -DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ../;
```
The last line was modified to point cmake to the correct path where python is located. Otherwise I believe it was picking up the python 2.7 default install on macOS. This ran successfully, and I get the final terminal output:

`Build files have been written to: /Users/rohanpatel/dev/dev_py/pykep/build_pykep`

When I go to run `sudo make -j2 install` I get the following terminal out:
```
pykep/core/CMakeFiles/core.dir/build.make:97: *** target pattern contains no `%'.  Stop.
make[1]: *** [pykep/core/CMakeFiles/core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
pykep/planet/CMakeFiles/planet.dir/build.make:82: *** target pattern contains no `%'.  Stop.
make[1]: *** [pykep/planet/CMakeFiles/planet.dir/all] Error 2
make: *** [all] Error 2
```

I am not sure how to proceed from here. Any ideas? I am new to cmake and boost. This is my first time compiling a library as well. 
I do not have an installation of Anaconda on my machine. I do have homebrew and have installed everything through it. 

Thank you for the help, I appreciate it.

**Comment by darioizzo** [comment]
Seems like some libraries are not found in your system. You can use ccmake to inspect what libraries are missing.

A few more notes: pykep Is available on conda for osx, did you consider using it?

Homebrew boost libraries are likely not compatible with the system python. If you really want to compile in homebrew you need to install python GCC and use those ones.

**Comment by rohanpatel747** [comment]
Thanks for the reply. I did originally try using conda but was having the issue: 
`TypeError: __init__() should return None, not 'NoneType'`
when trying to import it. That is why I tried to install it through homebrew. I can give the conda install another try. I am a bit confused though. When using 
`conda install pykep`
do I need to still compile the library and have boost/cmake for conda installed, or is that only if I was going to compile the library locally? 

Thanks again.

**Comment by darioizzo** [comment]
```conda install pykep``` is all you need. If not you can file an issue here.

**Comment by rohanpatel747** [comment]
Did a reinstall of conda with miniconda and I am happy to report that it does install with the conda package. Many thanks for the help. I was confused about the whole process as it was my first experience attempting to compile a library. Thanks for making it easy :)
