### ISSUE TITLE
TypeError: 'bool' object is not subscriptable,  line 72 in plot_planet

### ISSUE THREAD

**Issue by mkirby1995** [esa/pykep#117]
Running code from tutorial 01. line 6 under plot our trajectory throws TypeError

ax1 = udp.plot(pop.champion_x, axes = ax1)

**Comment by mkirby1995** [comment]
When plot_planet is called for the _pl2pl_N_impulses class only a single bool is passed, the plot_planet method wants a tuple.

**Comment by darioizzo** [comment]
will fix in the next release, thanks for reporting.

**Comment by mkirby1995** [comment]
This is fixed 

See new error about plot_kepler
