### ISSUE TITLE
UnboundLocalError: local variable 'r' referenced before assignment

### ISSUE THREAD

**Issue by mkirby1995** [esa/pykep#120]
Line 231 in _plots.py - under plot_kepler

r is being referenced before assignment

    # We calculate the spacecraft position at each dt
    for i in range(N):
        x[i] = r[0] / units
        y[i] = r[1] / units
        z[i] = r[2] / units
        r, v = propagate_lagrangian(r0, v0, dt, mu)

I copied code over to my env, moved the propagate_lagrangian line to top of for loop. This fixed it.

    # We calculate the spacecraft position at each dt
    for i in range(N):
        r, v = propagate_lagrangian(r0, v0, dt, mu)
        x[i] = r[0] / units
        y[i] = r[1] / units
        z[i] = r[2] / units

**Comment by darioizzo** [comment]
fixed in #119
