### ISSUE TITLE
Have gtoc planets optional in the build

### ISSUE THREAD

**Issue by darioizzo** [esa/pykep#17]
The GTOC related planets should be only compiled if a corresponding option in activated in CMAKE.

**Comment by ChrisAndre** [comment]
Is this issue still open after the planet refactor? I'll go ahead and address it, as I had it working earlier, but for the pre-refactor version.

**Comment by darioizzo** [comment]
Not really. The problem is that providing this option creates a lot of issues when importing classes that are using the gtoc asteroids (for example the example 6). 

I am no longer sure, at this point, that we want to complicate the import of PyKEP further detecting weather the option is activated or not ..... It does not seem that the advantage of not compiling the planets would suffice to justify such a nuisance. If you agree I would close the issue and have tou focus elsewhere.

**Comment by ChrisAndre** [comment]
It can be closed then.
