### ISSUE TITLE
Building PyKEP and PyGMO (PaGMO) into the Anaconda Environment under Mac OS X

### ISSUE THREAD

**Issue by OrbitalMechanic** [esa/pykep#18]
I'm attempting to build PyKEP, PyGMO (PaGMO) on a MacBook Pro running Mac OS X ver. 10.10.2 into an Anconda Python environment. 

When I used the version of PyKEP obtained  from git via the command git clone https://github.com/esa/pykep.git and following the installation directions at http://esa.github.io/pykep/installation.html# (for PyKEP) and http://esa.github.io/pygmo/install.html (for PyGMO) I have been able to build PyGMO and PyKEP to /urar/local/lib/python2.7/site-packages instead of /Users/user/anaconda/lib/python2.7/site-packages. 

When I the version from sourceforge, http://sourceforge.net/projects/keptoolbox/files/Others/, it installs but it causes python in Anaconda to stop running giving the following error message:

                        Fatal Python error: PyThreadState_Get: no current thread
                        Abort trap: 6

Any ideas?

Please advise.

**Comment by darioizzo** [comment]
PyKEP and PyGMO sourceforge repositories are not maintained anymore and should not be used. Please only use github.

Recently we changed the build system for both PyKEP and PyGMO, we are still cleaning it up, so get the latest versions from github, they will build and locate automatically the site-packages directory of the correct python. (check the cmake output in any case).

In case you need to change python version, select it via the CMake variable PYTHON_EXECUTABLE, all the rest will be automatically detected.

In case you want to change the installation site-packages directory (no longer defaulted to /usr/local/lib/pythonx.x/site-packages, but automatically detected), you can use the PYTHON_MODULES_DIR CMake variable (check also the new docs at http://esa.github.io/pykep/installation.html)

Let us know if all goes well ....

**Comment by OrbitalMechanic** [comment]
Dario Izzo,

Thank you for responding to my question so quickly.

I followed your suggestion, installed PyKEP and it installed in the Anaconda directory as I wanted. However, when I went yo see if the PyKEP would be included in the list of modules I got the following error message from python:

        Fatal Python error: PyThreadState_Get: no current thread
        Abort trap: 6


Any thoughts on what this error is, how it was caused and how to fix it?

Please advise.

Sam Dupree.

**Comment by OrbitalMechanic** [comment]
Dario Izzo,

Thank you for responding to my question so quickly.

I followed your suggestion, installed PyKEP and it installed in the 
Anaconda directory as I wanted. However, when I went yo see if the PyKEP 
would be included in the list of modules I got the following error 
message from python:

        Fatal Python error: PyThreadState_Get: no current thread
        Abort trap: 6


Any thoughts on what this error is, how it was caused and how to fix it?

Please advise.

Sam Dupree.

**Comment by darioizzo** [comment]
This error shows up when a module tries to use a python library that is different than the one the interpreter uses, that is, when you mix two different pythons. Probably the anaconda python and the system python are being mixed somewhere ....

Can you post the output of cmake? (say for PyKEP, no PyGMO)

Dario

**Comment by OrbitalMechanic** [comment]
Dario,

Attached are two files. The first is a screen snp showing the 
configuration generated by CMake. The second one is a log showing the 
output up to and including the make step.

Hope this helps.

Sam Dupree.



On 02/26/2015 02:25:02, Dario Izzo wrote:
>
> This error shows up when a module tries to use a python library that 
> is different than the one the interpreter uses, that is, when you mix 
> two different pythons. Probably the anaconda python and the system 
> python are being mixed somewhere ....
>
> Can you post the output of cmake? (say for PyKEP, no PyGMO)
>
> Dario
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/esa/pykep/issues/18#issuecomment-76133451>.
>



users-MacBook-Pro:~ user$ 
users-MacBook-Pro:~ user$ 
users-MacBook-Pro:~ user$ git clone https://github.com/esa/pykep.git
Cloning into 'pykep'...
remote: Counting objects: 2514, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 2514 (delta 37), reused 0 (delta 0), pack-reused 2435
Receiving objects: 100% (2514/2514), 3.51 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1691/1691), done.
Checking connectivity... done.
users-MacBook-Pro:~ user$ 
users-MacBook-Pro:~ user$ cd pykep
users-MacBook-Pro:pykep user$ mkdir build
users-MacBook-Pro:pykep user$ cd build
users-MacBook-Pro:build user$ ccmake ../


users-MacBook-Pro:build user$ make
Scanning dependencies of target keplerian_toolbox_static
[  1%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/epoch.cpp.o
[  3%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/lambert_problem.cpp.o
[  5%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/sims_flanagan/leg.cpp.o
[  7%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/sims_flanagan/spacecraft.cpp.o
[  9%] Building C object src/CMakeFiles/keplerian_toolbox_static.dir/core_functions/jorba.c.o
[ 11%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet.cpp.o
[ 13%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/asteroid_gtoc2.cpp.o
[ 15%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/asteroid_gtoc5.cpp.o
[ 17%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/asteroid_gtoc7.cpp.o
[ 19%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet_mpcorb.cpp.o
[ 21%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet_ss.cpp.o
[ 23%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet_js.cpp.o
[ 25%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet_tle.cpp.o
[ 27%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/Util.cpp.o
[ 29%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/Tle.cpp.o
[ 31%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/SolarPosition.cpp.o
[ 33%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/SGP4.cpp.o
[ 35%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/OrbitalElements.cpp.o
[ 37%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/Observer.cpp.o
[ 39%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/Eci.cpp.o
Linking CXX static library libkeplerian_toolbox_static.a
[ 39%] Built target keplerian_toolbox_static
Scanning dependencies of target main
[ 41%] Building CXX object CMakeFiles/main.dir/main.cpp.o
Linking CXX executable main
[ 41%] Built target main
Scanning dependencies of target keplerian_toolbox
[ 43%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/epoch.cpp.o
[ 45%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/lambert_problem.cpp.o
[ 47%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/sims_flanagan/leg.cpp.o
[ 49%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/sims_flanagan/spacecraft.cpp.o
[ 50%] Building C object src/CMakeFiles/keplerian_toolbox.dir/core_functions/jorba.c.o
[ 52%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet.cpp.o
[ 54%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/asteroid_gtoc2.cpp.o
[ 56%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/asteroid_gtoc5.cpp.o
[ 58%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/asteroid_gtoc7.cpp.o
[ 60%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet_mpcorb.cpp.o
[ 62%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet_ss.cpp.o
[ 64%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet_js.cpp.o
[ 66%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet_tle.cpp.o
[ 68%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/Util.cpp.o
[ 70%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/Tle.cpp.o
[ 72%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/SolarPosition.cpp.o
[ 74%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/SGP4.cpp.o
[ 76%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/OrbitalElements.cpp.o
[ 78%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/Observer.cpp.o
[ 80%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/Eci.cpp.o
Linking CXX shared library libkeplerian_toolbox.dylib
[ 80%] Built target keplerian_toolbox
Scanning dependencies of target _core
[ 82%] Building CXX object PyKEP/core/CMakeFiles/_core.dir/core.cpp.o
Linking CXX shared library _core.so
[ 82%] Built target _core
Scanning dependencies of target _sims_flanagan
[ 84%] Building CXX object PyKEP/sims_flanagan/CMakeFiles/_sims_flanagan.dir/sims_flanagan.cpp.o
Linking CXX shared library _sims_flanagan.so
[ 84%] Built target _sims_flanagan
Scanning dependencies of target lambert_test
[ 86%] Building CXX object tests/CMakeFiles/lambert_test.dir/lambert_test.cpp.o
Linking CXX executable lambert_test
[ 86%] Built target lambert_test
Scanning dependencies of target leg_s_test
[ 88%] Building CXX object tests/CMakeFiles/leg_s_test.dir/leg_s_test.cpp.o
Linking CXX executable leg_s_test
[ 88%] Built target leg_s_test
Scanning dependencies of target propagate_lagrangian_test
[ 90%] Building CXX object tests/CMakeFiles/propagate_lagrangian_test.dir/propagate_lagrangian_test.cpp.o
Linking CXX executable propagate_lagrangian_test
[ 90%] Built target propagate_lagrangian_test
Scanning dependencies of target propagate_lagrangian_u_test
[ 92%] Building CXX object tests/CMakeFiles/propagate_lagrangian_u_test.dir/propagate_lagrangian_u_test.cpp.o
Linking CXX executable propagate_lagrangian_u_test
[ 92%] Built target propagate_lagrangian_u_test
Scanning dependencies of target propagate_taylor_jorba_test
[ 94%] Building CXX object tests/CMakeFiles/propagate_taylor_jorba_test.dir/propagate_taylor_jorba_test.cpp.o
Linking CXX executable propagate_taylor_jorba_test
[ 94%] Built target propagate_taylor_jorba_test
Scanning dependencies of target propagate_taylor_s_test
[ 96%] Building CXX object tests/CMakeFiles/propagate_taylor_s_test.dir/propagate_taylor_s_test.cpp.o
Linking CXX executable propagate_taylor_s_test
[ 96%] Built target propagate_taylor_s_test
Scanning dependencies of target propagate_taylor_test
[ 98%] Building CXX object tests/CMakeFiles/propagate_taylor_test.dir/propagate_taylor_test.cpp.o
Linking CXX executable propagate_taylor_test
[ 98%] Built target propagate_taylor_test
Scanning dependencies of target sgp4_test
[100%] Building CXX object tests/CMakeFiles/sgp4_test.dir/sgp4_test.cpp.o
Linking CXX executable sgp4_test
[100%] Built target sgp4_test
users-MacBook-Pro:build user$

**Comment by OrbitalMechanic** [comment]
Dario,

I believe this is what you really wanted to see:

users-MacBook-Pro:build user$ cmake ../
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- OS detected: Darwin
-- CXX Compiler detected: Clang
-- CMake additional search path for libraries: /usr/local/lib
-- Performing Test CLANG_TEMPLATE_DEPTH
-- Performing Test CLANG_TEMPLATE_DEPTH - Success
-- Enabling '-ftemplate-depth=256' compiler flag required since boost 1.54.
-- Performing Test ALL_C11
-- Performing Test ALL_C11 - Success
-- Enabling '-std=c++11' compiler flag
-- CXX compilation flags:  -ftemplate-depth=256 -std=c++11
-- Required Boost libraries: serialization;date_time
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   serialization
--   date_time
-- Detected Boost version: 105700
-- Boost include dirs: /opt/local/include
-- Boost libraries: 
/opt/local/lib/libboost_serialization-mt.dylib;/opt/local/lib/libboost_date_time-mt.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/pykep/build
users-MacBook-Pro:build user$


Hope this helps.

Sam Dupree

**Comment by Juanlu001** [comment]
@OrbitalMechanic if you want to install PyKEP in Anaconda you should check this out:

https://github.com/Juanlu001/conda-recipes/blob/pykep/pykep/

Notice that if you don't properly select your boost version you might be affected by #13.

**Comment by darioizzo** [comment]
I need the output of cmake after you have activated the PyKEP option, so that O can check the python libraries autodetected, can you post that?

P.S. Have you deleted PyGMO and PYKEP from /usr/local/lib/python2.7/site-packages? If you have a PYTHONPATH pointing there, you may be loading the old modules (compiled for a different python)

**Comment by OrbitalMechanic** [comment]
I'm not exactly sure I have the right output from ccmake, but I've 
attached a screen snap of cmake after setting the BUILD_PYKEP flag to 
the ON position and entering c to configure cmake.

Hope this helps.

Sam Dupree.

**Comment by OrbitalMechanic** [comment]
I'm not familiar with doing installs in conda.

I was able to download build.sh, meta.yaml and run_test.sh. I noticed in 
build.sh some environmental variables.

  * What are the setting for these variables?
  * I assume that I don't need to modify meta.yaml and/or run_test.sh.
    Is this correct?
  * How do I run conda to build and install PyKEP?

Looking forward to hearing from you.

Sam Dupree.

**Comment by darioizzo** [comment]
Sam,

in order to help I need you to post the output of cmake after you have activated the BUILD_PYKEP flag.
In your build directory type:

```bash
cmake ../ -DBUILD_PYKEP="ON" 
```

and post the output here.

**Comment by OrbitalMechanic** [comment]
The following is what cmake ../ -DBUILD_PYKEP="ON"  outputs in my build subdirectory.

users-MacBook-Pro:~ user$ git clone https://github.com/esa/pykep.git
Cloning into 'pykep'...
remote: Counting objects: 2514, done.
remote: Total 2514 (delta 0), reused 0 (delta 0), pack-reused 2514
Receiving objects: 100% (2514/2514), 3.49 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1711/1711), done.
Checking connectivity... done.
users-MacBook-Pro:~ user$ cd pykep
users-MacBook-Pro:pykep user$ mkdir build
users-MacBook-Pro:pykep user$ cd build
users-MacBook-Pro:build user$ cmake ../ -DBUILD_PYKEP="ON" 
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- OS detected: Darwin
-- CXX Compiler detected: Clang
-- CMake additional search path for libraries: /usr/local/lib
-- Performing Test CLANG_TEMPLATE_DEPTH
-- Performing Test CLANG_TEMPLATE_DEPTH - Success
-- Enabling '-ftemplate-depth=256' compiler flag required since boost 1.54.
-- Performing Test ALL_C11
-- Performing Test ALL_C11 - Success
-- Enabling '-std=c++11' compiler flag
-- CXX compilation flags:  -ftemplate-depth=256 -std=c++11
-- Found PythonInterp: /Users/user/anaconda/bin/python (found version "2.7.9") 
-- Python interpreter: /Users/user/anaconda/bin/python
-- Python interpreter verison: 2.7
-- Python includes path: /Users/user/anaconda/include/python2.7
-- Python modules install path: /Users/user/anaconda/lib/python2.7/site-packages
-- Python library name: /Users/user/anaconda/lib/libpython2.7.dylib
-- Required Boost libraries: serialization;date_time;python
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   serialization
--   date_time
--   python
-- Detected Boost version: 105700
-- Boost include dirs: /usr/local/boost_1_57_0
-- Boost libraries: /opt/local/lib/libboost_serialization-mt.dylib;/opt/local/lib/libboost_date_time-mt.dylib;/opt/local/lib/libboost_python-mt.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/pykep/build
users-MacBook-Pro:build user$

**Comment by darioizzo** [comment]
Ok, this looks ok to me. can you then type

```bash
echo $PYTHONPATH
```

**Comment by darioizzo** [comment]
and 
```bash
otool -L  /opt/local/lib/libboost_python-mt.dylib
```

**Comment by OrbitalMechanic** [comment]
Below you'll observe that $PYTHONPATH is empty and displayed is the result of the otool -L /opt/local/lib/libboost-python-mt.dylib command.

Last login: Fri Feb 27 08:41:12 on console
users-MacBook-Pro:~ user$ cd pykep/build
users-MacBook-Pro:build user$ echo $PYTHONPATH

users-MacBook-Pro:build user$ otool -L /opt/local/lib/libboost-python-mt.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /opt/local/lib/libboost-python-mt.dylib (No such file or directory)
users-MacBook-Pro:build user$

**Comment by OrbitalMechanic** [comment]
Sorry about the otool command, I just caught  it. The output is:

users-MacBook-Pro:build user$ otool -L  /opt/local/lib/libboost_python-mt.dylib
/opt/local/lib/libboost_python-mt.dylib:
	/opt/local/lib/libboost_python-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
users-MacBook-Pro:build user$

**Comment by darioizzo** [comment]
There you go, your boost libraries are linking to the homebrew python, not the conda python!! This likely creates the problem as you have a library mismatch. 

You need either to:

1) rebuild boost somehow telling it to link to the conda python library /Users/user/anaconda/lib/libpython2.7.dylib

2) Use homebrew python for everything

Having said this, I am no osx expert and maybe other people here can help you as I know that some user have been able to use conda with PyKEP and PyGMO
