### ISSUE TITLE
make test in PyKEP under Anaconda fail

### ISSUE THREAD

**Issue by OrbitalMechanic** [esa/pykep#19]
I'm attempting to install PyKEP on a MacBook Pro under Mac OS X ver. 10.10.2 under the Anaconda python environment.

I've rebuilt Boost ver. 1.57.0 under the Anaconda Python environment per the directions on http://www.boost.org/doc/libs/1_57_0/more/getting_started/unix-variants.html#easy-build-and-install (section 5.1 on that page). I have not yet installed PyGMO. The following shows the commands and results in building PyKEP:

users-MacBook-Pro:build user$ cmake -DBUILD_PYKEP="ON"  \
>       -DPYTHON_EXECUTABLE=/Users/user/anaconda/bin/python2.7  \
>       -DPYTHON_INCLUDE_DIR=/Users/user/anaconda/include/python2.7  \
>       -DPYTHON_LIBRARY=/Users/user/anaconda/lib/python2.7/config/libpython2.7.a   \
>       -DBOOST_ROOT=/Users/user/boost_1_57_0_anaconda  ..
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- OS detected: Darwin
-- CXX Compiler detected: Clang
-- CMake additional search path for libraries: /usr/local/lib
-- Performing Test CLANG_TEMPLATE_DEPTH
-- Performing Test CLANG_TEMPLATE_DEPTH - Success
-- Enabling '-ftemplate-depth=256' compiler flag required since boost 1.54.
-- Performing Test ALL_C11
-- Performing Test ALL_C11 - Success
-- Enabling '-std=c++11' compiler flag
-- CXX compilation flags:  -ftemplate-depth=256 -std=c++11
-- Found PythonInterp: /Users/user/anaconda/bin/python2.7 (found version "2.7.9") 
-- Python interpreter: /Users/user/anaconda/bin/python2.7
-- Python interpreter verison: 2.7
-- Python includes path: /Users/user/anaconda/include/python2.7
-- Python modules install path: /Users/user/anaconda/lib/python2.7/site-packages
-- Python library name: /Users/user/anaconda/lib/libpython2.7.dylib
-- Required Boost libraries: serialization;date_time;python
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   serialization
--   date_time
--   python
-- Detected Boost version: 105700
-- Boost include dirs: /Users/user/boost_1_57_0_anaconda/include
-- Boost libraries: /Users/user/boost_1_57_0_anaconda/lib/libboost_serialization.dylib;/Users/user/boost_1_57_0_anaconda/lib/libboost_date_time.dylib;/Users/user/boost_1_57_0_anaconda/lib/libboost_python.dylib
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_LIBRARY

-- Build files have been written to: /Users/user/pykep/build
users-MacBook-Pro:build user$ make
Scanning dependencies of target keplerian_toolbox_static
[  1%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/epoch.cpp.o
[  3%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/lambert_problem.cpp.o
[  5%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/sims_flanagan/leg.cpp.o
[  7%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/sims_flanagan/spacecraft.cpp.o
[  9%] Building C object src/CMakeFiles/keplerian_toolbox_static.dir/core_functions/jorba.c.o
[ 11%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet.cpp.o
[ 13%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/asteroid_gtoc2.cpp.o
[ 15%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/asteroid_gtoc5.cpp.o
[ 17%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/asteroid_gtoc7.cpp.o
[ 19%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet_mpcorb.cpp.o
[ 21%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet_ss.cpp.o
[ 23%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet_js.cpp.o
[ 25%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/planets/planet_tle.cpp.o
[ 27%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/Util.cpp.o
[ 29%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/Tle.cpp.o
[ 31%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/SolarPosition.cpp.o
[ 33%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/SGP4.cpp.o
[ 35%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/OrbitalElements.cpp.o
[ 37%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/Observer.cpp.o
[ 39%] Building CXX object src/CMakeFiles/keplerian_toolbox_static.dir/third_party/libsgp4/Eci.cpp.o
Linking CXX static library libkeplerian_toolbox_static.a
[ 39%] Built target keplerian_toolbox_static
Scanning dependencies of target main
[ 41%] Building CXX object CMakeFiles/main.dir/main.cpp.o
Linking CXX executable main
[ 41%] Built target main
Scanning dependencies of target keplerian_toolbox
[ 43%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/epoch.cpp.o
[ 45%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/lambert_problem.cpp.o
[ 47%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/sims_flanagan/leg.cpp.o
[ 49%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/sims_flanagan/spacecraft.cpp.o
[ 50%] Building C object src/CMakeFiles/keplerian_toolbox.dir/core_functions/jorba.c.o
[ 52%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet.cpp.o
[ 54%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/asteroid_gtoc2.cpp.o
[ 56%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/asteroid_gtoc5.cpp.o
[ 58%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/asteroid_gtoc7.cpp.o
[ 60%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet_mpcorb.cpp.o
[ 62%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet_ss.cpp.o
[ 64%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet_js.cpp.o
[ 66%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/planets/planet_tle.cpp.o
[ 68%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/Util.cpp.o
[ 70%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/Tle.cpp.o
[ 72%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/SolarPosition.cpp.o
[ 74%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/SGP4.cpp.o
[ 76%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/OrbitalElements.cpp.o
[ 78%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/Observer.cpp.o
[ 80%] Building CXX object src/CMakeFiles/keplerian_toolbox.dir/third_party/libsgp4/Eci.cpp.o
Linking CXX shared library libkeplerian_toolbox.dylib
[ 80%] Built target keplerian_toolbox
Scanning dependencies of target _core
[ 82%] Building CXX object PyKEP/core/CMakeFiles/_core.dir/core.cpp.o
Linking CXX shared library _core.so
[ 82%] Built target _core
Scanning dependencies of target _sims_flanagan
[ 84%] Building CXX object PyKEP/sims_flanagan/CMakeFiles/_sims_flanagan.dir/sims_flanagan.cpp.o
Linking CXX shared library _sims_flanagan.so
[ 84%] Built target _sims_flanagan
Scanning dependencies of target lambert_test
[ 86%] Building CXX object tests/CMakeFiles/lambert_test.dir/lambert_test.cpp.o
Linking CXX executable lambert_test
[ 86%] Built target lambert_test
Scanning dependencies of target leg_s_test
[ 88%] Building CXX object tests/CMakeFiles/leg_s_test.dir/leg_s_test.cpp.o
Linking CXX executable leg_s_test
[ 88%] Built target leg_s_test
Scanning dependencies of target propagate_lagrangian_test
[ 90%] Building CXX object tests/CMakeFiles/propagate_lagrangian_test.dir/propagate_lagrangian_test.cpp.o
Linking CXX executable propagate_lagrangian_test
[ 90%] Built target propagate_lagrangian_test
Scanning dependencies of target propagate_lagrangian_u_test
[ 92%] Building CXX object tests/CMakeFiles/propagate_lagrangian_u_test.dir/propagate_lagrangian_u_test.cpp.o
Linking CXX executable propagate_lagrangian_u_test
[ 92%] Built target propagate_lagrangian_u_test
Scanning dependencies of target propagate_taylor_jorba_test
[ 94%] Building CXX object tests/CMakeFiles/propagate_taylor_jorba_test.dir/propagate_taylor_jorba_test.cpp.o
Linking CXX executable propagate_taylor_jorba_test
[ 94%] Built target propagate_taylor_jorba_test
Scanning dependencies of target propagate_taylor_s_test
[ 96%] Building CXX object tests/CMakeFiles/propagate_taylor_s_test.dir/propagate_taylor_s_test.cpp.o
Linking CXX executable propagate_taylor_s_test
[ 96%] Built target propagate_taylor_s_test
Scanning dependencies of target propagate_taylor_test
[ 98%] Building CXX object tests/CMakeFiles/propagate_taylor_test.dir/propagate_taylor_test.cpp.o
Linking CXX executable propagate_taylor_test
[ 98%] Built target propagate_taylor_test
Scanning dependencies of target sgp4_test
[100%] Building CXX object tests/CMakeFiles/sgp4_test.dir/sgp4_test.cpp.o
Linking CXX executable sgp4_test
[100%] Built target sgp4_test

Lastly, I did a make test to test the above build as a check prior to doing the install and got the following results:

users-MacBook-Pro:build user$ make test
Running tests...
Test project /Users/user/pykep/build
    Start 1: Testing_Multiple_Revolution_Lambert's_Solver
1/8 Test #1: Testing_Multiple_Revolution_Lambert's_Solver ........................................***Exception: Other  0.10 sec
    Start 2: Testing_Keplerian_propagation_via_Lagrange_Coefficients_and_osculating_elements
2/8 Test #2: Testing_Keplerian_propagation_via_Lagrange_Coefficients_and_osculating_elements .....***Exception: Other  0.08 sec
    Start 3: Testing_Keplerian_propagation_via_Lagrange_Coefficients_and_universal_variables
3/8 Test #3: Testing_Keplerian_propagation_via_Lagrange_Coefficients_and_universal_variables .....***Exception: Other  0.07 sec
    Start 4: Testing_Taylor_propagation_of_an_inertially_fixed_thrust_PyKEP_implementation
4/8 Test #4: Testing_Taylor_propagation_of_an_inertially_fixed_thrust_PyKEP_implementation .......***Exception: Other  0.07 sec
    Start 5: Testing_Taylor_propagation_of_an_inertially_fixed_thrust_Jorba_implementation
5/8 Test #5: Testing_Taylor_propagation_of_an_inertially_fixed_thrust_Jorba_implementation .......***Exception: Other  0.07 sec
    Start 6: Testing_Taylor_propagation_of_an_inertially_fixed_thrust_in_the_Sundmann_Variable
6/8 Test #6: Testing_Taylor_propagation_of_an_inertially_fixed_thrust_in_the_Sundmann_Variable ...***Exception: Other  0.07 sec
    Start 7: Testing_Leg_in_The_Sundmann_Variable
7/8 Test #7: Testing_Leg_in_The_Sundmann_Variable ................................................***Exception: Other  0.07 sec
    Start 8: Testing_SGP4_propagation
8/8 Test #8: Testing_SGP4_propagation ............................................................***Exception: Other  0.07 sec

0% tests passed, 8 tests failed out of 8

Total Test time (real) =   0.65 sec

The following tests FAILED:
	  1 - Testing_Multiple_Revolution_Lambert's_Solver (OTHER_FAULT)
	  2 - Testing_Keplerian_propagation_via_Lagrange_Coefficients_and_osculating_elements (OTHER_FAULT)
	  3 - Testing_Keplerian_propagation_via_Lagrange_Coefficients_and_universal_variables (OTHER_FAULT)
	  4 - Testing_Taylor_propagation_of_an_inertially_fixed_thrust_PyKEP_implementation (OTHER_FAULT)
	  5 - Testing_Taylor_propagation_of_an_inertially_fixed_thrust_Jorba_implementation (OTHER_FAULT)
	  6 - Testing_Taylor_propagation_of_an_inertially_fixed_thrust_in_the_Sundmann_Variable (OTHER_FAULT)
	  7 - Testing_Leg_in_The_Sundmann_Variable (OTHER_FAULT)
	  8 - Testing_SGP4_propagation (OTHER_FAULT)
Errors while running CTest
make: *** [test] Error 8
users-MacBook-Pro:build user$ 

Let me say from the beginning I'm not a C++ expert, yet having said that what do I need to do to fix this problem and proceed?

Please advise.

**Comment by darioizzo** [comment]
If the make test fails that is a purely c++ problem, not a python problem. Since this does not happen and is not reproducible on our systems (we also test on osx clang 6) it is probably related to some local set-up you have made in the past.

Not really sure how to help, the first thing, probably is to get a better debug info by going in the test directory and running the test individually to try producing some meaningful output. This is what I get, for example on the lambert test, on my Maverick:

```bash
cd build/test
./lambert_test 
Max error: 1.86077e-08
Average Error: 1.69485e-13
Number of Problems Solved: 940236
```

I suggest to:

1) remove the pykep folder
2) reclone from esa master
3) mkdir build
4) cd build
5) cmake ../
6) make
7) make install
8) make test
9) cd test
10) ./lambert_test 

Can you post the output of all of the above?

Dario

**Comment by OrbitalMechanic** [comment]
Before rebuilding PyKEP, I ran lambert_test and observed that PyKEP was not finding the dynamically loaded libraries in /User/user/anaconda/lib. Once I added /User/user/anaconda/lib to DYLD_LIBRARY_PATH and to LD_LIBRARY_PATH environment variables everything worked.

Thank you for all your help. I sincerely appreciated it.
Sam.
