### ISSUE TITLE
Compile the win32 and win64 binaries for the PyKEP 1.2.1

### ISSUE THREAD

**Issue by krzysztof** [esa/pykep#20]
Compile the four windows binaries of PyKEP (release [1.2.1](https://github.com/esa/pykep/tree/1.2.1), i.e. from commit c493e11dd58ebe5c8c3ae313768ecdf8f2fb2edb):
- win32 / Python 2.7
- win32 / Python 3
- win64 / Python 2.7
- win64 / Python 3

**Comment by darioizzo** [comment]
This needs a windows system with minGW or (even better MSVC) with boost libraries installed. The rest should go rather smooth as the code was compiled under windows successfully only a few months back.

**Comment by darioizzo** [comment]
pykep now in pypi
