### ISSUE TITLE
Build stops after barabasi-albert.cpp.o on Ubuntu 12.04

### ISSUE THREAD

**Issue by githubmjb** [esa/pykep#31]
I have had numerous unsuccessful attempts over the past 2 years at building pagmo on Mac OS, Debian 7, Windows and recently Ubuntu 12.04.

The highest boost version officially available for Ubuntu 12.04 seems to be 1.48. Using libboost1.55 causes a segmentation error in the gcc compiler. Compilation is being done on a Parallels virtual server with 2gb ram and 14 processors. PyKEP isalready  running fine on the Ubuntu 12.04 although this has also been made to work on all previous attempts on Mac OS, Debian and Windows.

With main selected in Cmake, the build process progresses without error  as far as  77% but stops at barabasi-albert.cpp with a reference to adj_list_serialize_bug_fix.hpp:15:0 and thereafter about 200 further lines of other error messages mostly referencing serialization errors. 

The CMakeList.txt has been edited to swap the $MANDATORY_LIBRARIES directive after pagmo_static as given in point 5 of the compilation guide.

Can anyone help me with this issue?

**Comment by ChrisAndre** [comment]
Can you post the make output?

I've installed both on a few different flavors of Ubuntu (Mint, Lubuntu). Might it be that you did not fully install boost with bootstrap.sh? I recall having serialization symbols missing once; it may have been reinstalling that fixed it. Serialization is one of the modules that must be compiled, IIRC. My other guess would be to update gcc if you can.

**Comment by darioizzo** [comment]
When setting up the Travis virtual machine I had at one point, problems with gcc as it was terminating with seg faults. The problem seemed to be related to the limited RAM available on the VM, I then solved it by calling make -j3 instead of make -j5. Ad this was a work around, I then switched to clang that is known to be better in terms of memory usage and in fact all works better in a limited ram machine.

Have a look at the travis VM set up (.yml file in the root dir).

Ad fora the problem with serialization, please, as Chris pointed out, post the output of cmake and make, so that se can try to help.

**Comment by githubmjb** [comment]
Thanks for the response.  I am trying the fixes suggested by Chris and will then see what happens. If there is still an issue I will post the output from Cmke as requested. If it works then I shall post the actions taken to make it work.Many thanks for the contact as I have tried to compile pagmo on many systems all without success. The closest I got was on mac os 10.6 and libboost1.49 where it compiles (sometimes falling over at around 97% and sometimes completing) but then the python code encounters a break and does not run. PyKep compiles first time and has run reliably on a range of systems.It would be really great to get pagmo working as currently I am using matlab which is very slow for trajectory optimisation even with snopt.Regards M J Burgess-----Original Message-----

**Comment by darioizzo** [comment]
OK .. Let us know ...

On osx your crash is most likely due to linking to the system wide python library, while using boost-python compiled and linked to the homebrew ( or macport or equivalent) python library.

In case you intend to use snopt, you need the libraries and you may have to link in additional stuff according to whether you compiled snopt using f77 or gfortran

**Comment by githubmjb** [comment]
I will update gcc (highest available seems to be 4.7) and rebuild boost and then post an update and the make update.-----Original Message-----

**Comment by githubmjb** [comment]
For OSX I gave up as it was difficult to know what was being used or linked.

For Ubuntu 12.04:
I have now built boost  1.52 and pagmo builds to 100% but does not link. This issue seems to arise either from a boost build problem from the mpi and the number of cores or perhaps a messed up compiler toolchain. I will attend to these items and then post the initial and updated logs from make.

regards

**Comment by githubmjb** [comment]
Output of make attached as requested. Log is from the second run of make after the first run which completed to 76%. Full log is of first make available if the would be useful. Regards-----Original Message-----

**Comment by githubmjb** [comment]
Following an attempt with libboost 1.52 I have restored the system back to 1.49 as making pygmo and examples produced a spectacular flood of error messages. 

Building main,  the build halts at 77% as before on barabasi-albert.cpp with the error messages as in the file attached in the email reply to the previous post (as the web interface on github does not seem to accept a text file attached to the post). I have updated  G++/GCC to 4.8 from 4.6 since the previous build attempt as suggested by ChrisAndre and installed libboost1.49 and the log is produced after the update.

**Comment by ChrisAndre** [comment]
Could you upload the log to a service like pastebin.com? I am unable to see the log through either github or the email notifications. Thanks!

**Comment by githubmjb** [comment]
Would a link to dropbox or idrive work?

Regards

M J Burgess

**Comment by ChrisAndre** [comment]
Yes. It doesn't appear that there is any way to attach files to github issues, unfortunately. You could try directly pasting it here, though. In fact, in case someone runs across the same issue, that might be the best option.

**Comment by githubmjb** [comment]
Log from make while building pagmo main:[--- start log --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------[  1%] Building CXX object src/CMakeFiles/pagmo_static.dir/topology/barabasi_albert.cpp.oIn file included from /home/admin/pagmo/src/topology/../adj_list_serialize_bug_fix.hpp:15:0,                 from /home/admin/pagmo/src/topology/../serialization.h:28,                 from /home/admin/pagmo/src/topology/../rng.h:38,                 from /home/admin/pagmo/src/topology/barabasi_albert.cpp:35:/usr/include/boost/graph/adjacency_list.hpp: In instantiation of 'typename boost::graph_property<boost::adjacency_list<OutEdgeListS, VertexListS, DirectedS, VertexProperty, EdgeProperty, GraphProperty, EdgeListS>, Tag>::type& boost::get_property(boost::adjacency_list<OutEdgeListS, VertexListS, DirectedS, VertexProperty, EdgeProperty, GraphProperty, EdgeListS>&, Tag) [with OEL = boost::vecS; VL = boost::vecS; D = boost::bidirectionalS; VP = boost::no_property; EP = pagmo::topology::base::edge_properties; GP = boost::no_property; EL = boost::listS; Tag = boost::graph_all_t; typename boost::graph_property<boost::adjacency_list<OutEdgeListS, VertexListS, DirectedS, VertexProperty, EdgeProperty, GraphProperty, EdgeListS>, Tag>::type = boost::detail::error_property_not_found]':/home/admin/pagmo/src/topology/../adj_list_serialize_bug_fix.hpp:107:84:   required from 'void boost::serialization::load(Archive&, boost::adjacency_list<OEL, VL, D, VP, EP, GP, EL>&, unsigned int) [with Archive = boost::archive::text_iarchive; OEL = boost::vecS; VL = boost::vecS; D = boost::bidirectionalS; VP = boost::no_property; EP = pagmo::topology::base::edge_properties; GP = boost::no_property; EL = boost::listS]'/usr/include/boost/serialization/split_free.hpp:58:22:   required from 'static void boost::serialization::free_loader<Archive, T>::invoke(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::no_property, pagmo::topology::base::edge_properties, boost::no_property, boost::listS>]'/usr/include/boost/serialization/split_free.hpp:74:38:   required from 'void boost::serialization::split_free(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::no_property, pagmo::topology::base::edge_properties, boost::no_property, boost::listS>]'/home/admin/pagmo/src/topology/../adj_list_serialize_bug_fix.hpp:116:61:   required from 'void boost::serialization::serialize(Archive&, boost::adjacency_list<OEL, VL, D, VP, EP, GP, EL>&, unsigned int) [with Archive = boost::archive::text_iarchive; OEL = boost::vecS; VL = boost::vecS; D = boost::bidirectionalS; VP = boost::no_property; EP = pagmo::topology::base::edge_properties; GP = boost::no_property; EL = boost::listS]'/usr/include/boost/serialization/serialization.hpp:128:27:   required from 'void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::no_property, pagmo::topology::base::edge_properties, boost::no_property, boost::listS>]'/usr/include/boost/archive/detail/iserializer.hpp:192:5:   [ skipping 35 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]/usr/include/boost/serialization/export.hpp:86:1:   required from 'struct boost::archive::detail::ptr_serialization_support<boost::archive::text_iarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/detail/register_archive.hpp:25:8:   required from 'struct boost::archive::detail::_ptr_serialization_support<boost::archive::text_iarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/text_iarchive.hpp:150:1:   required by substitution of 'template<class Serializable> typename boost::archive::detail::_ptr_serialization_support<boost::archive::text_iarchive, Serializable>::type boost::archive::detail::instantiate_ptr_serialization(Serializable*, boost::archive::text_iarchive*, boost::archive::detail::adl_tag) [with Serializable = pagmo::topology::barabasi_albert]'/usr/include/boost/serialization/export.hpp:132:58:   required from 'void boost::archive::detail::extra_detail::guid_initializer<T>::export_guid(mpl_::false_) const [with T = pagmo::topology::barabasi_albert; mpl_::false_ = mpl_::bool_<false>]'/usr/include/boost/serialization/export.hpp:142:61:   required from 'const boost::archive::detail::extra_detail::guid_initializer<T>& boost::archive::detail::extra_detail::guid_initializer<T>::export_guid() const [with T = pagmo::topology::barabasi_albert]'/home/admin/pagmo/src/topology/barabasi_albert.cpp:165:1:   required from here/usr/include/boost/graph/adjacency_list.hpp:512:51: error: invalid initialization of non-const reference of type 'boost::graph_property<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::no_property, pagmo::topology::base::edge_properties, boost::no_property, boost::listS>, boost::graph_all_t>::type& {aka boost::detail::error_property_not_found&}' from an rvalue of type 'boost::detail::error_property_not_found'     return get_property_value(*g.m_property, Tag());                                                   ^In file included from /usr/include/boost/multi_index/detail/index_node_base.hpp:22:0,                 from /usr/include/boost/multi_index/detail/node_type.hpp:23,                 from /usr/include/boost/multi_index/detail/index_base.hpp:21,                 from /usr/include/boost/multi_index/detail/base_type.hpp:21,                 from /usr/include/boost/multi_index_container.hpp:33,                 from /usr/include/boost/graph/named_graph.hpp:16,                 from /usr/include/boost/graph/adjacency_list.hpp:45,                 from /home/admin/pagmo/src/topology/../adj_list_serialize_bug_fix.hpp:15,                 from /home/admin/pagmo/src/topology/../serialization.h:28,                 from /home/admin/pagmo/src/topology/../rng.h:38,                 from /home/admin/pagmo/src/topology/barabasi_albert.cpp:35:/usr/include/boost/serialization/access.hpp: In instantiation of 'static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_oarchive; T = boost::detail::error_property_not_found]':/usr/include/boost/serialization/serialization.hpp:69:69:   required from 'void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_oarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/serialization/serialization.hpp:128:27:   required from 'void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::text_oarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/archive/detail/oserializer.hpp:152:5:   required from 'void boost::archive::detail::oserializer<Archive, T>::save_object_data(boost::archive::detail::basic_oarchive&, const void*) const [with Archive = boost::archive::text_oarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/archive/detail/oserializer.hpp:101:1:   required from 'class boost::archive::detail::oserializer<boost::archive::text_oarchive, boost::detail::error_property_not_found>'/usr/include/boost/archive/detail/oserializer.hpp:253:13:   required from 'static void boost::archive::detail::save_non_pointer_type<Archive>::save_standard::invoke(Archive&, const T&) [with T = boost::detail::error_property_not_found; Archive = boost::archive::text_oarchive]'/usr/include/boost/archive/detail/oserializer.hpp:308:28:   [ skipping 57 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]/usr/include/boost/serialization/export.hpp:86:1:   required from 'struct boost::archive::detail::ptr_serialization_support<boost::archive::text_oarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/detail/register_archive.hpp:25:8:   required from 'struct boost::archive::detail::_ptr_serialization_support<boost::archive::text_oarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/text_oarchive.hpp:111:1:   required by substitution of 'template<class Serializable> typename boost::archive::detail::_ptr_serialization_support<boost::archive::text_oarchive, Serializable>::type boost::archive::detail::instantiate_ptr_serialization(Serializable*, boost::archive::text_oarchive*, boost::archive::detail::adl_tag) [with Serializable = pagmo::topology::barabasi_albert]'/usr/include/boost/serialization/export.hpp:132:58:   required from 'void boost::archive::detail::extra_detail::guid_initializer<T>::export_guid(mpl_::false_) const [with T = pagmo::topology::barabasi_albert; mpl_::false_ = mpl_::bool_<false>]'/usr/include/boost/serialization/export.hpp:142:61:   required from 'const boost::archive::detail::extra_detail::guid_initializer<T>& boost::archive::detail::extra_detail::guid_initializer<T>::export_guid() const [with T = pagmo::topology::barabasi_albert]'/home/admin/pagmo/src/topology/barabasi_albert.cpp:165:1:   required from here/usr/include/boost/serialization/access.hpp:118:9: error: 'struct boost::detail::error_property_not_found' has no member named 'serialize'         t.serialize(ar, file_version);         ^/usr/include/boost/serialization/access.hpp: In instantiation of 'static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::detail::error_property_not_found]':/usr/include/boost/serialization/serialization.hpp:69:69:   required from 'void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/serialization/serialization.hpp:128:27:   required from 'void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/archive/detail/iserializer.hpp:192:5:   required from 'void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = boost::archive::text_iarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/archive/detail/iserializer.hpp:120:1:   required from 'class boost::archive::detail::iserializer<boost::archive::text_iarchive, boost::detail::error_property_not_found>'/usr/include/boost/archive/detail/iserializer.hpp:387:13:   required from 'static void boost::archive::detail::load_non_pointer_type<Archive>::load_standard::invoke(Archive&, const T&) [with T = boost::detail::error_property_not_found; Archive = boost::archive::text_iarchive]'/usr/include/boost/archive/detail/iserializer.hpp:439:28:   [ skipping 61 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]/usr/include/boost/serialization/export.hpp:86:1:   required from 'struct boost::archive::detail::ptr_serialization_support<boost::archive::text_iarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/detail/register_archive.hpp:25:8:   required from 'struct boost::archive::detail::_ptr_serialization_support<boost::archive::text_iarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/text_iarchive.hpp:150:1:   required by substitution of 'template<class Serializable> typename boost::archive::detail::_ptr_serialization_support<boost::archive::text_iarchive, Serializable>::type boost::archive::detail::instantiate_ptr_serialization(Serializable*, boost::archive::text_iarchive*, boost::archive::detail::adl_tag) [with Serializable = pagmo::topology::barabasi_albert]'/usr/include/boost/serialization/export.hpp:132:58:   required from 'void boost::archive::detail::extra_detail::guid_initializer<T>::export_guid(mpl_::false_) const [with T = pagmo::topology::barabasi_albert; mpl_::false_ = mpl_::bool_<false>]'/usr/include/boost/serialization/export.hpp:142:61:   required from 'const boost::archive::detail::extra_detail::guid_initializer<T>& boost::archive::detail::extra_detail::guid_initializer<T>::export_guid() const [with T = pagmo::topology::barabasi_albert]'/home/admin/pagmo/src/topology/barabasi_albert.cpp:165:1:   required from here/usr/include/boost/serialization/access.hpp:118:9: error: 'struct boost::detail::error_property_not_found' has no member named 'serialize'/usr/include/boost/serialization/access.hpp: In instantiation of 'static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = boost::detail::error_property_not_found]':/usr/include/boost/serialization/serialization.hpp:69:69:   required from 'void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/serialization/serialization.hpp:128:27:   required from 'void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/archive/detail/oserializer.hpp:152:5:   required from 'void boost::archive::detail::oserializer<Archive, T>::save_object_data(boost::archive::detail::basic_oarchive&, const void*) const [with Archive = boost::archive::binary_oarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/archive/detail/oserializer.hpp:101:1:   required from 'class boost::archive::detail::oserializer<boost::archive::binary_oarchive, boost::detail::error_property_not_found>'/usr/include/boost/archive/detail/oserializer.hpp:253:13:   required from 'static void boost::archive::detail::save_non_pointer_type<Archive>::save_standard::invoke(Archive&, const T&) [with T = boost::detail::error_property_not_found; Archive = boost::archive::binary_oarchive]'/usr/include/boost/archive/detail/oserializer.hpp:308:28:   [ skipping 61 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]/usr/include/boost/serialization/export.hpp:86:1:   required from 'struct boost::archive::detail::ptr_serialization_support<boost::archive::binary_oarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/detail/register_archive.hpp:25:8:   required from 'struct boost::archive::detail::_ptr_serialization_support<boost::archive::binary_oarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/binary_oarchive.hpp:59:1:   required by substitution of 'template<class Serializable> typename boost::archive::detail::_ptr_serialization_support<boost::archive::binary_oarchive, Serializable>::type boost::archive::detail::instantiate_ptr_serialization(Serializable*, boost::archive::binary_oarchive*, boost::archive::detail::adl_tag) [with Serializable = pagmo::topology::barabasi_albert]'/usr/include/boost/serialization/export.hpp:132:58:   required from 'void boost::archive::detail::extra_detail::guid_initializer<T>::export_guid(mpl_::false_) const [with T = pagmo::topology::barabasi_albert; mpl_::false_ = mpl_::bool_<false>]'/usr/include/boost/serialization/export.hpp:142:61:   required from 'const boost::archive::detail::extra_detail::guid_initializer<T>& boost::archive::detail::extra_detail::guid_initializer<T>::export_guid() const [with T = pagmo::topology::barabasi_albert]'/home/admin/pagmo/src/topology/barabasi_albert.cpp:165:1:   required from here/usr/include/boost/serialization/access.hpp:118:9: error: 'struct boost::detail::error_property_not_found' has no member named 'serialize'/usr/include/boost/serialization/access.hpp: In instantiation of 'static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_iarchive; T = boost::detail::error_property_not_found]':/usr/include/boost/serialization/serialization.hpp:69:69:   required from 'void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_iarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/serialization/serialization.hpp:128:27:   required from 'void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_iarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/archive/detail/iserializer.hpp:192:5:   required from 'void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = boost::archive::binary_iarchive; T = boost::detail::error_property_not_found]'/usr/include/boost/archive/detail/iserializer.hpp:120:1:   required from 'class boost::archive::detail::iserializer<boost::archive::binary_iarchive, boost::detail::error_property_not_found>'/usr/include/boost/archive/detail/iserializer.hpp:387:13:   required from 'static void boost::archive::detail::load_non_pointer_type<Archive>::load_standard::invoke(Archive&, const T&) [with T = boost::detail::error_property_not_found; Archive = boost::archive::binary_iarchive]'/usr/include/boost/archive/detail/iserializer.hpp:439:28:   [ skipping 61 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]/usr/include/boost/serialization/export.hpp:86:1:   required from 'struct boost::archive::detail::ptr_serialization_support<boost::archive::binary_iarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/detail/register_archive.hpp:25:8:   required from 'struct boost::archive::detail::_ptr_serialization_support<boost::archive::binary_iarchive, pagmo::topology::barabasi_albert>'/usr/include/boost/archive/binary_iarchive.hpp:96:1:   required by substitution of 'template<class Serializable> typename boost::archive::detail::_ptr_serialization_support<boost::archive::binary_iarchive, Serializable>::type boost::archive::detail::instantiate_ptr_serialization(Serializable*, boost::archive::binary_iarchive*, boost::archive::detail::adl_tag) [with Serializable = pagmo::topology::barabasi_albert]'/usr/include/boost/serialization/export.hpp:132:58:   required from 'void boost::archive::detail::extra_detail::guid_initializer<T>::export_guid(mpl_::false_) const [with T = pagmo::topology::barabasi_albert; mpl_::false_ = mpl_::bool_<false>]'/usr/include/boost/serialization/export.hpp:142:61:   required from 'const boost::archive::detail::extra_detail::guid_initializer<T>& boost::archive::detail::extra_detail::guid_initializer<T>::export_guid() const [with T = pagmo::topology::barabasi_albert]'/home/admin/pagmo/src/topology/barabasi_albert.cpp:165:1:   required from here/usr/include/boost/serialization/access.hpp:118:9: error: 'struct boost::detail::error_property_not_found' has no member named 'serialize'make[2]: *** [src/CMakeFiles/pagmo_static.dir/topology/barabasi_albert.cpp.o] Error 1make[1]: *** [src/CMakeFiles/pagmo_static.dir/all] Error 2make: *** [all] Error 2--------------------------------------------------------------------------------------------------------------------------------------------------------------------------- end log -------------]-----Original Message-----

**Comment by ChrisAndre** [comment]
While my knowledge of boost and C++ errors is limited, it looks like this issue is internal to the boost library setup you have. The type 'boost::detail::error_property_not_found' seems to be setting it off.

I've gone through several Ubuntu images lately and tried getting PyKEP/PyGMO on most. I've found that the most foolproof way to install boost is through the package manager, as installing from source had several aspects in which it could go wrong (and did go wrong a few times). My suggestion at this point would be to uninstall boost completely and go through apt-get instead:

sudo apt-get install libboost-all-dev

I found a thread that may be of some use: http://askubuntu.com/questions/308657/installing-boost-on-12-04-have-ran-sudo-apt-get-install-libboost-all-dev-now

I just reimaged my Ubuntu 14.04 system today and I was able to get PyKEP/PyGMO running fine after installing boost that way. I imagine your 12.04 wont have any issues with this.

Good luck!

**Comment by githubmjb** [comment]
Thanks. 

My initial approach was to do all standard installs using apt- get and standard packages but this did not seem to work as pagmo requires boost higher than 1.46.

 So I then installed 1.48 with apt-get which is when problems arose. Various attempts to remove boost failed and ccmake complained when boost 1.46 was removed.

I have also come to the conclusion that boost is definitely the problem so I am going to restore a clean image of the system and start again. building Boost is indeed a very dark art.

I see you have working versions of pykep/pygmo so perhaps I could come back to you for your installation steps if things do not work.

I will certainly need to draw on the good luck you have sent me since this is my Nth + 1 attempt at getting pagmo working. 

Regards

M J Burgess

**Comment by githubmjb** [comment]
Hi

Just to thank ChrisAndre and Dario for the hints on building Pagmo /PyKEP.

I have now managed to create a largely working system on Ubuntu 14.04 which runs all the examples except for PyKEP example 4. Example 4 always seems to fail before finding a solution.

I have not exactly managed to track down why Pagmo did not build although  system memory (at least 2GB) and a clean copy of boost 1.55 were contributing factors. 

If I do I will post the issue and the resolution as a matter of record in case other users have suffered similar difficulties.

Regards

M J Burgess

**Comment by darioizzo** [comment]
Ok thanks ....
