### ISSUE TITLE
planet.keplerian.ref_mjd2000 should be float not epoch

### ISSUE THREAD

**Issue by dhennes** [esa/pykep#40]
pl = planet.keplerian(epoch(0), (1., 0., 0), (0., 1., 0.), 1., 0., 0., 0.)
    type(pl.ref_mjd2000)
    >>> PyKEP.core._core.epoch

The instance object `ref_mjd2000` of `PyKEP.planet.keplerian` should be a `float` and not `epoch`. Alternatively, one could rename the it to `ref_epoch`.

**Comment by darioizzo** [comment]
Done. Both exists now.
