### ISSUE TITLE
Python: NameError with leg_s

### ISSUE THREAD

**Issue by ChrisAndre** [esa/pykep#43]
> from PyKEP.sims_flanagan import *
> leg()
> <...>
> leg_s()
> NameError: name 'leg_s' is not defined

The Boost python seems to have `leg_s` defined alongside `leg` though:
https://github.com/esa/pykep/blob/master/PyKEP/sims_flanagan/sims_flanagan.cpp#L288

This breaks run_example4() in PyKEP.examples

**Comment by ChrisAndre** [comment]
Turned out to be rather simple, the `__init__.py` for the `sims_flanagan` module does not import `leg_s`.

**Comment by darioizzo** [comment]
Fixed example 4 for release 2.0 #71
