### ISSUE TITLE
Make test fails on Ubuntu with Anaconda 32-bit Python 2.7

### ISSUE THREAD

**Issue by voldyy** [esa/pykep#44]
I completed all the necessary preparation steps (including installation of cmake, boost, etc.), and when I run the make command everything builds properly until this point:

[ 98%] Building CXX object PyKEP/core/CMakeFiles/_core.dir/core.cpp.o
/home/mp/pykep/PyKEP/core/core.cpp:1893039:287: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
Preprocessed source stored into /tmp/cceGTORs.out file, please attach this to your bugreport.
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/_usr_lib_gcc_i686-linux-gnu_4.6_cc1plus.0.crash'
make[2]: *** [PyKEP/core/CMakeFiles/_core.dir/core.cpp.o] Error 1
make[1]: *** [PyKEP/core/CMakeFiles/_core.dir/all] Error 2
make: *** [all] Error 2

Any idea how I can resolve this issue?

**Comment by darioizzo** [comment]
My guess (but I maybe wrong) is that you do not have enough ram and GCC crashes when compiling the memory heavy boost binding.

I suggest you to use clang, it is known to be less memory heavy. Let me know if this solves the issue

**Comment by voldyy** [comment]
Thanks for the quick response. Installing clang now, I'll let you know if it works.

**Comment by voldyy** [comment]
My build worked, but PyKEP installed to the "wrong" python. It installed to the base version of python present on my system, but I would like to install it to the Anaconda version of python on my machine. Does that require me to change the PYTHON_EXECUTABLE variable? If so, which file do I point it to? I can't find the python3.3m file in my Anaconda bin folder.

**Comment by darioizzo** [comment]
Yes you need to change the python executable to the one you will use. Then the libs and headers will be updated automatically using the distutil of the selected python

**Comment by voldyy** [comment]
Thanks, worked like a charm.
