### ISSUE TITLE
Problem getting the example to work

### ISSUE THREAD

**Issue by ennehekma** [esa/pykep#46]
Hi,

To test my installation of PyKEP I made a script lam.py with the following code:
*from PyKEP import *
examples.run_example2()*
(source: http://esa.github.io/pykep/examples/ex2.html)

When I run this code I get the following error message.

*Traceback (most recent call last):
  File "lam.py", line 1, in <module>
    from PyKEP import *
  File "/usr/lib/python2.7/dist-packages/PyKEP/__init__.py", line 45, in <module>
    from PyKEP import core, sims_flanagan, orbit_plots, examples, trajopt, phasing, util, planet
  File "/usr/lib/python2.7/dist-packages/PyKEP/core/__init__.py", line 3, in <module>
    from PyKEP.core._core import _get_AU, _get_JR, _get_DAY2SEC, _get_DAY2YEAR, _get_DEG2RAD, _get_EARTH_VELOCITY, _get_G0, _get_MU_SUN, _get_RAD2DEG, _get_SEC2DAY
ImportError: /usr/lib/python2.7/dist-packages/PyKEP/core/_core.so: undefined symbol: _ZTIN5boost6python15instance_holderE*

I don't know what to do anymore. I tried running it with both python 2.7 and 3.4 and tried to relink the boost libraries with different versions of python. 
Many thanks in advance, 
Enne

**Comment by darioizzo** [comment]
Which OS are you running?

**Comment by ennehekma** [comment]
Sorry, forgot to mention. Ubuntu 14.04

**Comment by darioizzo** [comment]
Can you post here the output of cmake ../ ? From the build directory?

**Comment by ennehekma** [comment]
-- OS detected: Linux
-- CXX Compiler detected: GNU
-- CMake additional search path for libraries: 
-- Enabling '-Wall' compiler flag.
-- Enabling '-Wextra' compiler flag.
-- Enabling '-Wnoexcept' compiler flag.
-- Enabling '-Wdisabled-optimization' compiler flag.
-- Enabling '-ffast-math' compiler flag.
-- Enabling '-std=c++11' compiler flag
-- Enabling '-fPIC' compiler flag
-- CXX compilation flags:  -Wall -Wextra -Wnoexcept -Wdisabled-optimization -ffast-math -std=c++11
-- C compilation flags:  -fPIC
-- Python interpreter: /usr/bin/python2
-- Python interpreter verison: 
-- Python includes path: 
-- Python modules install path: 
-- Python library name: 
-- Required Boost libraries: serialization;date_time;python
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   serialization
--   date_time
--   python
-- Detected Boost version: 105900
-- Boost include dirs: /home/enne/Scripts/boost/include
-- Boost libraries: /home/enne/Scripts/boost/lib/libboost_serialization.so;/home/enne/Scripts/boost/lib/libboost_date_time.so;/home/enne/Scripts/boost_1_59_0/libs
-- Configuring done
WARNING: Target "_core" requests linking to directory "/home/enne/Scripts/boost_1_59_0/libs".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "_sims_flanagan" requests linking to directory "/home/enne/Scripts/boost_1_59_0/libs".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "_util" requests linking to directory "/home/enne/Scripts/boost_1_59_0/libs".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "_planet" requests linking to directory "/home/enne/Scripts/boost_1_59_0/libs".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/enne/Scripts/Pykep/pykep/build

**Comment by darioizzo** [comment]
I think you may be messing up the linking to boost libraries. Its not clear what boost you are linking to (see the Warning). Why are you not using the system wide boost? If you have a local boost installation, make sure headers and libraries are correct.

**Comment by ennehekma** [comment]
Thank you so far, I already fixed some problems with my boost installation but probably messed up some other things along the way. I will try to install boost from scratch again and see if I run into any problems.

**Comment by ennehekma** [comment]
Dear Dario,

Re-installed both Boost and PyKEP from scratch and it works now, sorry for disturbing you and many thanks anyway.

Best regards,
Enne

**Comment by EPiress** [comment]
Hey, 

I'm having problems running the same example as ennehekma did, and i also don't know why.
I've tried to re-install everything, but it always seems to end on the same error message: 

File "first.py", line 1, in <module>
    from PyKEP import *
  File "/usr/lib/python2.7/dist-packages/PyKEP/__init__.py", line 45, in <module>
    from PyKEP import core, sims_flanagan, orbit_plots, examples, trajopt, phasing, util, planet
  File "/usr/lib/python2.7/dist-packages/PyKEP/core/__init__.py", line 3, in <module>
    from PyKEP.core._core import _get_AU, _get_JR, _get_DAY2SEC, _get_DAY2YEAR, _get_DEG2RAD, _get_EARTH_VELOCITY, _get_G0, _get_MU_SUN, _get_RAD2DEG, _get_SEC2DAY
ImportError: libkeplerian_toolbox.so: cannot open shared object file: No such file or directory

cmake ../ gives me this output (clearly smth is wrong):

-- OS detected: Linux
-- CXX Compiler detected: GNU
-- CMake additional search path for libraries: 
-- Enabling '-Wall' compiler flag.
-- Enabling '-Wextra' compiler flag.
-- Enabling '-Wnoexcept' compiler flag.
-- Enabling '-Wdisabled-optimization' compiler flag.
-- Enabling '-ffast-math' compiler flag.
-- Enabling '-std=c++0x' compiler flag
-- Enabling '-fPIC' compiler flag
-- CXX compilation flags:  -Wall -Wextra -Wnoexcept -Wdisabled-optimization -ffast-math -std=c++0x
-- C compilation flags:  -fPIC
-- Python interpreter: /usr/bin/python
-- Python interpreter verison: 2.7
-- Python includes path: /usr/include/python2.7
-- Python modules install path: /usr/lib/python2.7/dist-packages
-- Python library name: /usr/lib/libpython2.7.so.1.0
-- Required Boost libraries: serialization;date_time;python
-- Detected Boost version: 104601
-- Boost include dirs: /usr/include
-- Boost libraries: /usr/lib/libboost_serialization-mt.so;/usr/lib/libboost_date_time-mt.so;/usr/lib/libboost_python.so
CMake Error at CMakeLists.txt:110 (FILE):
  file COPY cannot set permissions on
  "/home/epires/pykep/build/tests/sgp4_test.txt"


CMake Error at CMakeLists.txt:111 (FILE):
  file COPY cannot set permissions on
  "/home/epires/pykep/build/tests/C_G_1000012_2012_2017.bsp"


CMake Error at CMakeLists.txt:112 (FILE):
  file COPY cannot set permissions on
  "/home/epires/pykep/build/tests/pck00010.tpc"


CMake Error at CMakeLists.txt:113 (FILE):
  file COPY cannot set permissions on
  "/home/epires/pykep/build/tests/gm_de431.tpc"


-- Configuring incomplete, errors occurred!
CMake Error: Unable to open check cache file for write. /home/epires/pykep/build/CMakeFiles/cmake.check_cache


Help me please!
EPires

**Comment by darioizzo** [comment]
I think your problems are not with running the example but in general with installing under linux.
I would suggest to start from scratch.

```
git clone https://github.com/esa/pykep.git
mkdir build
ccmake ../
SELECT THE OPTION PYKEP, configure two times, then generate
cmake ../
```
After these steps whats the screen output?

**Comment by EPiress** [comment]
Hey Dario,

thank u so much for your fast answer!!
Well this is what i get now:

-- OS detected: Linux
-- CXX Compiler detected: GNU
-- CMake additional search path for libraries: 
-- Enabling '-Wall' compiler flag.
-- Enabling '-Wextra' compiler flag.
-- Enabling '-Wnoexcept' compiler flag.
-- Enabling '-Wdisabled-optimization' compiler flag.
-- Enabling '-ffast-math' compiler flag.
-- Enabling '-std=c++0x' compiler flag
-- Enabling '-fPIC' compiler flag
-- CXX compilation flags:  -Wall -Wextra -Wnoexcept -Wdisabled-optimization -ffast-math -std=c++0x
-- C compilation flags:  -fPIC
-- Python interpreter: /usr/bin/python
-- Python interpreter verison: 2.7
-- Python includes path: /usr/include/python2.7
-- Python modules install path: /usr/lib/python2.7/dist-packages
-- Python library name: /usr/lib/libpython2.7.so.1.0
-- Required Boost libraries: serialization;date_time;python
-- Detected Boost version: 104601
-- Boost include dirs: /usr/include
-- Boost libraries: /usr/lib/libboost_serialization-mt.so;/usr/lib/libboost_date_time-mt.so;/usr/lib/libboost_python.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/epires/pykep/build

**Comment by EPiress** [comment]
Even though everything seems fine with the installation, i still get this error message when i try to run example2:

Traceback (most recent call last):
  File "ex.py", line 1, in <module>
    from PyKEP import *
  File "/usr/lib/python2.7/dist-packages/PyKEP/__init__.py", line 45, in <module>
    from PyKEP import core, sims_flanagan, orbit_plots, examples, trajopt, phasing, util, planet
  File "/usr/lib/python2.7/dist-packages/PyKEP/core/__init__.py", line 3, in <module>
    from PyKEP.core._core import _get_AU, _get_JR, _get_DAY2SEC, _get_DAY2YEAR, _get_DEG2RAD, _get_EARTH_VELOCITY, _get_G0, _get_MU_SUN, _get_RAD2DEG, _get_SEC2DAY
ImportError: libkeplerian_toolbox.so: cannot open shared object file: No such file or directory

**Comment by darioizzo** [comment]
Ok great. So now everything looks correct. I guess you just need to type
```
ldconfig
```
this will update the library cache of linux.

**Comment by EPiress** [comment]
Ok, after running ldconfig, i get this:

File "ex.py", line 2, in <module>
    examples.run_example2()
  File "/usr/lib/python2.7/dist-packages/PyKEP/examples/_ex2.py", line 2, in run_example2
    import matplotlib as mpl
ImportError: No module named matplotlib

I'm sorry, but I'm a beginner in PyKEP and I am really lost!
Thank you for your help

**Comment by darioizzo** [comment]
well that is not a pykep related issue. You maybe should look into tutorials on python and its toolboxes.

matplotlib is one of them and with numpy and scipy is part of the standard python scientific computing toolset.

You may be able to install everything you need 
```
pip install numpy matplotlib scipy
```
if you have pip installed.

**Comment by EPiress** [comment]
Ok, thank you very much Dario!
