### ISSUE TITLE
JPL SPICE usage

### ISSUE THREAD

**Issue by voldyy** [esa/pykep#48]
I understand that JPL SPICE has been integrated into the latest version of PyKEP. How do I call SPICE functions. For example, say I want to load in a .bsp file using str2et. Is it possible to call this function using any tools from PyKEP?

**Comment by darioizzo** [comment]
Docs are missing on the spice integration. Next update should take care of that.

In the meantime time you can look athttps://github.com/esa/pykep/blob/master/PyKEP/util/util.cpp
And find the spice function or read the docs returned by python for the planet spice

**Comment by darioizzo** [comment]
Only ephemerides are exposed .... All other spice functions are not.

**Comment by voldyy** [comment]
Ok, thank you.
