### ISSUE TITLE
install problem under linux

### ISSUE THREAD

**Issue by sax25** [esa/pykep#51]
Hallo,

(sorry if my question sounds unprofessional or the is trivial to you - I have never ever before compiled anything myself - till pyKep everything I needed came via packetmanager)

I tried to follow the install instructions under https://esa.github.io/pykep/installation.html.

My system: (L)Ubuntu 14.04, Python installed: 2.7(default) and 3.4

(Before doing anything fancy like installing it for both versions, I decided to first try it on the default python, which links to 2.7)

Having the prerequisites installed, I created a directory and did the git pull 

> git clone https://github.com/esa/pykep.git

, which created a dir with the pykep files in it. So far, so good.

In the downloaded dir there was said to be a directory "keptoolbox", which nowhere was to be found. so I decided to take the "pykep"-dir instead and created the suggested "build"-dir there.

in build/ I called 

> ```
> ccmake ../
> ```

populated the fields with "c" and switched BUILD_PYKEP to ON. then pressed "g" (nothing happened) and then "q" to exit ccmake.

then typed

> make
> and all I got was a  "no targets"-error

2nd try: I changed to the pykep dir directly and did 

> ccmake .

again "g" and then "q" and then "make ". Same result as before: "no targets"-error

when I start ccmake and populate the fields it looks like this:

> BUILD_MAIN                       ON  
>  BUILD_PYKEP                      ON  
>  BUILD_SPICE                      OFF  
>  BUILD_TESTS                      ON  
>  CMAKE_BUILD_TYPE                 Release  
>  CMAKE_INSTALL_PREFIX             /usr/local  
>  INSTALL_HEADERS                  OFF  
>  PYTHON_EXECUTABLE                /usr/bin/python  
>  PYTHON_INCLUDE_DIR               /usr/include/python2.7  
>  PYTHON_LIBRARIES  
>  PYTHON_MODULES_DIR               /usr/lib/python2.7/dist-packages  
>  PYTHON_VERSION                   2.7                                                                   

Can anyone please help me? Is the install instruction outdated? 

*_Update: *_
I switched  my default python to 3.4 (wanted to change anyway) but still got the problems from above.

*_Update #2: *_
I tried the suggested specifying of the python version now:

> ccmake ../ -DBUILD_PYKEP="ON"  -DPYTHON_EXECUTABLE="/usr/bin/python3.3m"

and while populating with "c" got the error "boost_python3 missing some libraries". checked the packetmanager and there was no packet boost_python3. only libboost mpi python.

so I thought switching to 3.4 after installing boost was a bad idea. deinstalled boost, reinstalled boost.
same error from ccmake about the missing boost python3 libs

**Comment by darioizzo** [comment]
Not sure what you are doing wrong, but you need to first select your
options (PyKEP TEST HEADERS etc.) then  type c (configure) then c again and
then g (generate). It will generate the make file. CMAKE is a rather
standard build system, you can aslo find more information on the net ....

let us know,

Dario

**Comment by sax25** [comment]
ok - like I said - never build anything before :-)  

but I got somewhat farther: decided to download the boost source and build a boost python3 lib like suggested here

> https://eb2.co/blog/2012/03/building-boost-python-for-python-3-2/

and after that no more complaints from cmake. I did the make and make install. 

but now when in python i try "include PyKEP", there is an error about a missing library:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-74ce3e8e9de4> in <module>()
----> 1 import PyKEP

/usr/lib/python3/dist-packages/PyKEP/__init__.py in <module>()
     43 # We import the submodules
     44 ###########################################################
---> 45 from PyKEP import core, sims_flanagan, orbit_plots, examples, trajopt, phasing, util, planet
     46 
     47 # For convenience, bring all core classes into the root namespace when importing *.

/usr/lib/python3/dist-packages/PyKEP/core/__init__.py in <module>()
      1 # -*- coding: iso-8859-1 -*-
      2 # We import the proteced symbols we use in this file
----> 3 from PyKEP.core._core import _get_AU, _get_JR, _get_DAY2SEC, _get_DAY2YEAR, _get_DEG2RAD, _get_EARTH_VELOCITY, _get_G0, _get_MU_SUN, _get_RAD2DEG, _get_SEC2DAY
      4 from PyKEP.core._core import _epoch_type
      5 # We import symbols we use in this file

ImportError: libkeplerian_toolbox.so: cannot open shared object file: No such file or directory
```

which is correct, as i cant find any libkeplerian_toolbox.so on my system. the python module seems to be found, as "/usr/lib/python3/dist-packages/PyKEP/core/__init__.py" was found in the correct place. 

so how/where can I get this libkeplerian_toolbox.so file? 

oh - and while compiling boost for python 3 there was an error, but it installed nonetheless. so i ignored it. may be this is the culprit?

```
gcc.compile.c++ bin.v2/libs/iostreams/build/gcc-4.8/release/link-static/threading-multi/bzip2.o
libs/iostreams/src/bzip2.cpp:20:56: fatal error: bzlib.h: Datei oder Verzeichnis nicht gefunden
 #include "bzlib.h"  // Julian Seward's "bzip.h" header.
                                                        ^
compilation terminated.

    "g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -march=i686 -pthread -m32  -DBOOST_ALL_NO_LIB=1 -DBOOST_IOSTREAMS_USE_DEPRECATED -DNDEBUG  -I"." -c -o "bin.v2/libs/iostreams/build/gcc-4.8/release/link-static/threading-multi/bzip2.o" "libs/iostreams/src/bzip2.cpp"

...failed gcc.compile.c++ bin.v2/libs/iostreams/build/gcc-4.8/release/link-static/threading-multi/bzip2.o...
...skipped <pbin.v2/libs/iostreams/build/gcc-4.8/release/link-static/threading-multi>libboost_iostreams.a(clean) for lack of <pbin.v2/libs/iostreams/build/gcc-4.8/release/link-static/threading-multi>bzip2.o...
...skipped <pbin.v2/libs/iostreams/build/gcc-4.8/release/link-static/threading-multi>libboost_iostreams.a for lack of <pbin.v2/libs/iostreams/build/gcc-4.8/release/link-static/threading-multi>bzip2.o...
...skipped <p/usr/local/lib>libboost_iostreams.a for lack of <pbin.v2/libs/iostreams/build/gcc-4.8/release/link-static/threading-multi>libboost_iostreams.a...
```

**Comment by darioizzo** [comment]
When you type make install the terminal shows you the exact location where the library is copied. If its correctly copied into a system folder searched for libraries, you still may have to type ldconfig to update the library database. Otherwise you may move it manually or create a symbolic link.

**Comment by darioizzo** [comment]
outdated? pykep is now in PyPi
