### ISSUE TITLE
Installing PyKEP under Windows 64bit, Python 3

### ISSUE THREAD

**Issue by MJDiaz89** [esa/pykep#53]
Hi, PyKEP Team.

I have a Windows 10 64bit system with 64bit Anaconda (Python 3.5) installed.  I successfully installed PyKEP using the v1.2.2 64bit Python 3 (`PyKEP.1.2.2.64-bit.py3.msi`) pre-compiled Windows binaries in my Anaconda environment's site-packages directory.  The thing is, when I try to import it from Python, I get the following traceback error:
```
>>> import PyKEP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\test\lib\site-packages\PyKEP\__init__.py", line 45, in <module>
    from PyKEP import core, sims_flanagan, orbit_plots, examples, trajopt, phasing, util, planet
  File "C:\Anaconda3\envs\test\lib\site-packages\PyKEP\core\__init__.py", line 3, in <module>
    from PyKEP.core._core import _get_AU, _get_JR, _get_DAY2SEC, _get_DAY2YEAR, _get_DEG2RAD, _get_EARTH_VELOCITY, _get_G0, _get_MU_SUN, _get_RAD2DEG, _get_SEC2DAY
ImportError: DLL load failed: The specified module could not be found.
```

I also tried this on a Windows 7 64bit computer and had identical results. 

I Googled around and found that some users were experiencing "DLL load failed" errors (not related to PyKEP, just this error in general) that were due to missing MS Visual C DLLs, and they had luck installing the `msvcp71.dll` and `msvcr71.dll`, but that didn't help -- I still get the same traceback on both the Win7 and Win10 systems.

Any guidance on what the issue might be?

(No issues building PyKEP from source on several Linux machines, however!)

**Comment by darioizzo** [comment]
sorry windows support is minimal, we are aware, unfortunately we lack resources to make windows experience user friendly. Not sure what type of issue you are encountering we cannot help much.

**Comment by timnoinc** [comment]
To any future wanderers who find this, as I did, through google, I used depends.exe to find that core/_core.pyd was looking for a python34.dll. I installed python 3.4 instead of 3.6, but I think compiling your own PyKEP against 3.6 would work as well.

**Comment by darioizzo** [comment]
there should be a pip package working for win64 did you try pip install pykep?

**Comment by a093130** [comment]
Jumping in as "me too".  Been struggling with this build for a month.  With the above advice I was able to do a PIP install inside Anaconda3 with Python 3.6.  PyKep now works like a champ.  If I ever meet you, I'm buying you dinner.
