### ISSUE TITLE
Python modules have explicit framework links

### ISSUE THREAD

**Issue by iMichka** [esa/pykep#57]
Hi. I am one of the homebrew-science package managers. We distribute pykep through our package manager for OS X. Our CI is complaining about pykep being linked to a specific python:

> * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/opt/pykep/lib/python2.7/site-packages/PyKEP/core/_core.so
      /usr/local/opt/pykep/lib/python2.7/site-packages/PyKEP/planet/_planet.so
      /usr/local/opt/pykep/lib/python2.7/site-packages/PyKEP/sims_flanagan/_sims_flanagan.so
      /usr/local/opt/pykep/lib/python2.7/site-packages/PyKEP/util/_util.so

Here is the explanation about why it would be good if you could use the `-undefined dynamic_lookup` flag while linking under OS X:
http://blog.tim-smith.us/2015/09/python-extension-modules-os-x/

To control that this works well, you can use `otool -L` on the `.so` files, which should not mention any python libraries.

See https://github.com/Homebrew/homebrew-science/pull/4762 for reference. Could you please have a look at this? Thanks in advance.

**Comment by darioizzo** [comment]
Lookng into it, will let you know.

**Comment by darioizzo** [comment]
Does this fix the problem?

**Comment by iMichka** [comment]
Yes! Looks really good. I just tested, and I already some equivalent things in other projects built with cmake, the code looks right. Thanks for the fast fix.

We will use the patch as long as there is no new release. Thanks for all.

**Comment by darioizzo** [comment]
np and thanks for the report, we are not very "experts" on osx building :)
