### ISSUE TITLE
Load the SPICE Kernel files to compute the ephemerides

### ISSUE THREAD

**Issue by EPiress** [esa/pykep#58]
Hi,

So I am new to PYKEP, and I have been trying to compute some high precision ephemerides, from SPICE Kernels. 
My code is really simple, as I just want to get the ephemerides, before anything else. This is what I have so far:

from PyKEP import *

planet = planet.spice('EARTH', 'SUN', 'ECLIPJ2000', 'NONE', MU_SUN, MU_EARTH, EARTH_RADIUS, EARTH_RADIUS * 1.05)

r,v=planet.eph(epoch(5700,"mjd2000"))

And this is what I get:

Toolkit version: N0065
 
SPICE(NOLOADEDFILES) --
 
At least one SPK file needs to be loaded by SPKLEF before beginning a search.
 
A traceback follows.  The name of the highest level module is first.
spkezr_c --> SPKEZR --> SPKEZ --> SPKGEO --> SPKSFS
 
============================================================================
Traceback (most recent call last):
  File "/Users/eduardopires/PycharmProjects/01Pykep/test.py", line 7, in <module>
    r,v=planet.eph(epoch(5700,"mjd2000"))
RuntimeError: SPICE cannot compute the ephemerides, have you loaded all needed Kernel files?

Now I know I have to load the Kernels, but which Kernel should I load? 
And how do I actually load it?

Thanks in advance,
EPiress

**Comment by darioizzo** [comment]
You need to load the Kernels that contain the data you then want to query. So it really depends on what eph you want to compute.

The c++ or python function to call is load_spice_kernel. If you compiled PyKEP with SPICE you should find it in the main namespace.

Let me know

**Comment by EPiress** [comment]
Hey Dario,

Thank you for your fast answer. 
I have just re-compiled PyKEP, to make sure I included SPICE. But I can not find the function load_spice_kernel on Python!
One more thing, on the example

planet = planet.spice('EARTH', 'SUN', 'ECLIPJ2000', 'NONE', MU_SUN, MU_EARTH, EARTH_RADIUS, EARTH_RADIUS * 1.05)

which Kernel do I have to load? 
It would be great for me if you could show me an example of how to load the kernels.

Thanks again,
EPiress

**Comment by darioizzo** [comment]
Here is an output from my system:

In [1]: import PyKEP as pk

In [2]: pk.util.load_spice_kernel?
Docstring:
PyKEP.util.load_spice_kernel(file_name)

- file_name: string containing the kernel file to load

Loads the SPICE kernel specified by the filename into memory.

.. note::

   The kernel must be in memory before its used, for example, when
computing a planets.spice ephemerides

Example::

  util.load_spice_kernel('de432s.bsp')
Type:      function

Do you not get the same?

**Comment by EPiress** [comment]
Dario,

This is what I get:

>>>import PyKEP as pk
>>> pk.util.load_spice_kernel
<Boost.Python.function object at 0x7f924b62d350>
>>> 

What is wrong here?

**Comment by darioizzo** [comment]
nothing, you are just not calling the function and python tells you its a
function.

**Comment by darioizzo** [comment]
in my example by adding a question mark at the end I print the help

**Comment by EPiress** [comment]
This is what I get, when I add the question mark:

File "<stdin>", line 1
    pk.util.load_spice_kernel?
                             ^
SyntaxError: invalid syntax

**Comment by darioizzo** [comment]
that is probably because you are in python shell and not an ipython shell?

**Comment by darioizzo** [comment]
```
import PyKEP as pk
util.load_spice_kernel('de432s.bsp')
```

you do not need to read the help in any case .... the above will work if you have the file ...

**Comment by darioizzo** [comment]
I suggest you to use an ipython shell though ..... it will make your life easier

**Comment by EPiress** [comment]
Ok, so I was able to load a Kernel!

from PyKEP import *
util.load_spice_kernel('mar097.bsp')
planet = planet.spice('EARTH', 'SUN', 'ECLIPJ2000', 'NONE', MU_SUN, MU_EARTH, EARTH_RADIUS, EARTH_RADIUS * 1.05)
r,v=planet.eph(epoch(5700,"mjd2000"))

Do I have to have the Kernel in the same directory as the python file?
And in this specific case, I am able to get results, even though the kernels are for mars, and I want to compute the eph for the earth. 
So how do I choose the "correct" Kernel?

**Comment by darioizzo** [comment]
Probably the kernel of mars contains also the earth. If you get a result it means the info is there, otherwise there would be an error.
The kernel can be anywhere but you need to give then the full path or add the folder to the python path ...

**Comment by darioizzo** [comment]
Let me know when I can close this .... also you can chat on the gitter pykep channel next time instead of opening a ticket: https://gitter.im/esa/pykep

**Comment by EPiress** [comment]
Ok, thanks a lot!

**Comment by darioizzo** [comment]
One last think, do not call the variable ```planet```, call it something else, like ```earth``` otherwise you will shadow the whole module called planet

**Comment by spacebee3** [comment]
I am facing a similar issue -- the spice kernel is loaded correctly and gives results for Earth and Venus, however fails for other planets with this error message: "SPICE cannot compute the ephemerides, have you loaded all needed Kernel files?"

Am I missing some files?
