### ISSUE TITLE
PyKEP syntax error after PaGMO installation

### ISSUE THREAD

**Issue by Stardust404** [esa/pykep#70]
We installed on our CentOS 7 Machine PyKEP (clone from github, installation was followed from https://esa.github.io/pykep/installation.html). PyKEP alone worked fine.
After that, we installed PyGMO (clone from gitgub, installation was followed from http://esa.github.io/pygmo/install.html). Now we can use PyGMO, but as soon as we want to use PyKEP, we get an syntax error. 

```
>>> from PyKEP import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/PyKEP/__init__.py", line 48, in <module>
    from PyKEP import core, sims_flanagan, pontryagin, orbit_plots, examples, phasing, util, planet, trajopt
  File "/usr/lib/python2.7/site-packages/PyKEP/trajopt/__init__.py", line 17, in <module>
    from PyKEP.trajopt._indirect import _indirect_base, indirect_pt2pt, indirect_pl2pl, indirect_or2or, indirect_pt2or
  File "/usr/lib/python2.7/site-packages/PyKEP/trajopt/_indirect.py", line 195
    lb = [self.t0lb, self.Tlb, *[-1e2] * 7]
                               ^
SyntaxError: invalid syntax
```
Any ideas?

Please advise.
Thanks alot.

**Comment by darioizzo** [comment]
We are in the process of developing a new PyKEP compatible with pygmo2 and not with the old PyGMO 1.1.5 which is unsupported.

As a consequence we are trying out things and probably not testing properly under all architectures.

It seems like the ``lb = [self.t0lb, self.Tlb, *[-1e2] * 7]`` syntax of the new file _indirect.py is not liked by your python, not sure if it has to do with the 2.7 version or something else.

Anyway, you do not need the file _indirect.py, so you can (as a work around) just avoid to import it. Or install not the current PyKEP snapshot but the release version.

**Comment by Stardust404** [comment]
Thanks for your answer.

We tried to avoid to import "_indirect.py", didnt worked.
After that, we installed the official release version v1.3.9 ( https://github.com/esa/pykep/releases/tag/v1.3.9 ). Now we get another error:

```
>>> from PyKEP import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/PyKEP/__init__.py", line 47, in <module>
    from PyKEP.core import *
  File "/usr/lib/python2.7/site-packages/PyKEP/core/__init__.py", line 3, in <module>
    from PyKEP.core._core import _get_AU, _get_JR, _get_DAY2SEC, _get_DAY2YEAR, _get_DEG2RAD, _get_EARTH_VELOCITY, _get_EARTH_J2, _get_EARTH_RADIUS, _get_MU_EARTH, _get_G0, _get_MU_SUN, _get_RAD2DEG, _get_SEC2DAY
ImportError: /usr/lib/python2.7/site-packages/PyKEP/core/_core.so: undefined symbol: _ZN11kep_toolbox15lambert_problemC1ERKSt5arrayIdLm3EES4_RKdS6_RKiS8_
>>> 
```
Any Ideas?
Thanks in advance.

**Comment by darioizzo** [comment]
Not sure whats happening. What error did you get when not importing _indirect.py?

**Comment by Stardust404** [comment]
We just made the machine new, reinstalled PyKEP (v1.3.9) and PyGMO and now "from PyKEP import *" works again. 
But now we get 

```
>>> from PyKEP import *
>>> examples.run_example3()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'run_example3'
```
Example 2 from https://esa.github.io/pykep/examples/index.html works fine.

We guess, its because the PyGMO module doesnt work?
```
>>> from PyGMO import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/PyGMO/__init__.py", line 57, in <module>
    from PyGMO import core, algorithm, migration, problem, topology, test, util
  File "/usr/lib/python2.7/site-packages/PyGMO/core/__init__.py", line 2, in <module>
    from PyGMO.core._core import *
ImportError: libpagmo.so: cannot open shared object file: No such file or directory
>>> 
```

Any Ideas?
Thanks in advance.

**Comment by darioizzo** [comment]
did you compile and install the pagmo library?

**Comment by Stardust404** [comment]
We did the installation like in http://esa.github.io/pygmo/install.html (just without the optional packages except PyKEP. So we didnt turned "ON" during ccmake on said packages. Else it was the same).

**Comment by darioizzo** [comment]
This seems not to be a pykep issue, but an issue on your sstem.

 The libpagmo.so library is simply not found by your system. If its there it may be a matter of paths or simply running ``ldconfig`` to update the system library database ...

**Comment by Stardust404** [comment]
You were right. We solved the lib db issue on our machine and PyKEP and PyGMO are working fine... except with examples with (nseg=20), where it gave us the error

`TypeError: run_example1() got an unexpected keyword argument 'nseg'`

Any ideas?
Thanks so far and have a good weekend.
