### ISSUE TITLE
error when running examples with pygmo and SNOPT7

### ISSUE THREAD

**Issue by Guanli20131** [esa/pykep#81]
when I use snopt7 by running pygmo examples or pykep examples, I got ValueError:  in  code "pop = algo.evolve(pop)", but there is no problem when I run examples 1 and 2 in pykep.
My Computer : Widows10 64bit    Python3.6  64bit, with these libs intalled :

matplotlib            3.0.0
numpy                 1.15.2
pygmo                 2.4
pygmo-plugins-nonfree 0.4
pykep                 2.2
pyopt                 0.84
scipy                 1.1.0

I got a snopt libs and license from Standford's website, also the FORTAN and SNOPT_C interface libraries ,and copy them to "C:\Python\SnoptLib\". They are "snopt7.dll,  snopt7.lib,  snopt7.lic,  snopt7_c.dll,  snopt7_c.lib".

The Test code is from pygmo examples or pykep,  such as:
from pygmo import *
from pygmo_plugins_nonfree import snopt7
algo = algorithm(snopt7(screen_output = False, library = r"C:\Python\SnoptLib\snopt7_c.dll"))
algo.set_verbosity(1)
prob = problem(cec2006(prob_id = 1))
prob.c_tol = [1e-6]*9
pop = population(prob, 1)
pop = algo.evolve(pop) 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-0c689dd5d414> in <module>
      6 prob.c_tol = [1e-6]*9
      7 pop = population(prob, 1)
----> 8 pop = algo.evolve(pop)
ValueError:

when the SQP method is modified to NLOPT, there is no problem. So where is the trouble? Thank you for your answer.

**Comment by darioizzo** [comment]
Can you post the error message? Value error what?

**Comment by Guanli20131** [comment]
By running example 8 in PyKep with IPython, I got message below:
-----------------------------------------------------------------------------------------------
In [1]: import pykep as pk
In [2]: pk.examples.run_example8()

ValueError                                Traceback (most recent call last)
<ipython-input-2-a755e5a01f4e> in <module>
----> 1 pk.examples.run_example8()
c:\python\python36\lib\site-packages\pykep\examples\_ex8.py in run_example8(nseg)
     35
     36     # 4 - Solve the problem (evolve)
---> 37     pop = algo.evolve(pop)
     38
     39     # 5 - Inspect the solution
ValueError:
In [3]:
---------------------------------------------------------------------------  
There is no other message any more.
 When the row  "algo = algo_factory("snopt7")"  in example 8 was modified to "algo = algo_factory("slsqp")" , there is no error message displayed, and I got the right result after a short period running.

This is the parametre value when I run example 8 in Pycharm IDE, I do not know whether it is useful for you to position the problem.
-----------------------------------------------------------------------------------------------------
axis = {AxesSubplot} AxesSubplot(0.125,0.11;0.775x0.77)
nseg = {int} 40
pop = {population} Problem name: <class 'pykep.examples._ex_utilities.add_gradient'>\n\tGlobal dimension:\t\t\t129\n\tInteger dimension:\t\t\t0\n\tFitness dimension:\t\t\t50\n\tNumber of objectives:\t\t\t1\n\tEquality constraints dimension:\t\t7\n\tInequality constraints dimension:\t42\n\tTolerances on constraints: [1e-005, 1e-005, 1e-005, 1e-005, 1e-005, ... ]\n\tLower bounds: [1100, 200, 100, -3500, -3500, ... ]\n\tUpper bounds: [1400, 750, 1000, 3500, 3500, ... ]\n\n\tHas gradient: true\n\tUser implemented gradient sparsity: false\n\tExpected gradients: 6450\n\tHas hessians: false\n\tUser implemented hessians sparsity: false\n\n\tFitness evaluations: 23042\n\tGradient evaluations: 16068\n\n\tThread safety: none\n\nPopulation size: 1\n\nList of individuals: \n#0:\n\tID:\t\t\t14259131561737751408\n\tDecision vector:\t[1286.56, 665.77, 905.563, 3247.08, 1258.91, ... ]\n\tFitness vector:\t\t[-905.563, -7.40042e-008, -7.65504e-008, 4.63234e-009, 4.18154e-008, ... ]\n\nChampion decision vector: [1286.56, 665.77, 905.563, 3247.08, 1258.91, ... ]\nChampion fitness: [-...
 champion_f = {ndarray}  
 champion_x = {ndarray}  
 problem = {problem} Problem name: <class 'pykep.examples._ex_utilities.add_gradient'>\n\tGlobal dimension:\t\t\t129\n\tInteger dimension:\t\t\t0\n\tFitness dimension:\t\t\t50\n\tNumber of objectives:\t\t\t1\n\tEquality constraints dimension:\t\t7\n\tInequality constraints dimension:\t42\n\tTolerances on constraints: [1e-005, 1e-005, 1e-005, 1e-005, 1e-005, ... ]\n\tLower bounds: [1100, 200, 100, -3500, -3500, ... ]\n\tUpper bounds: [1400, 750, 1000, 3500, 3500, ... ]\n\n\tHas gradient: true\n\tUser implemented gradient sparsity: false\n\tExpected gradients: 6450\n\tHas hessians: false\n\tUser implemented hessians sparsity: false\n\n\tFitness evaluations: 23042\n\tGradient evaluations: 16068\n\n\tThread safety: none\n
prob = {problem} Problem name: <class 'pykep.examples._ex_utilities.add_gradient'>\n\tGlobal dimension:\t\t\t129\n\tInteger dimension:\t\t\t0\n\tFitness dimension:\t\t\t50\n\tNumber of objectives:\t\t\t1\n\tEquality constraints dimension:\t\t7\n\tInequality constraints dimension:\t42\n\tTolerances on constraints: [1e-005, 1e-005, 1e-005, 1e-005, 1e-005, ... ]\n\tLower bounds: [1100, 200, 100, -3500, -3500, ... ]\n\tUpper bounds: [1400, 750, 1000, 3500, 3500, ... ]\n\n\tHas gradient: true\n\tUser implemented gradient sparsity: false\n\tExpected gradients: 6450\n\tHas hessians: false\n\tUser implemented hessians sparsity: false\n\n\tFitness evaluations: 1\n\tGradient evaluations: 0\n\n\tThread safety: none\n
 c_tol = {ndarray}  
udp = {add_gradient} <pykep.examples._ex_utilities.add_gradient object at 0x00000230BB04DC18>
 prob = {problem} Problem name: <class 'pykep.trajopt._direct.direct_pl2pl'>\n\tGlobal dimension:\t\t\t129\n\tInteger dimension:\t\t\t0\n\tFitness dimension:\t\t\t50\n\tNumber of objectives:\t\t\t1\n\tEquality constraints dimension:\t\t7\n\tInequality constraints dimension:\t42\n\tTolerances on constra
 udp_inner = {direct_pl2pl} <pykep.trajopt._direct.direct_pl2pl object at 0x00000230BB04D7B8>
 with_grad = {bool} True 
-----------------------------------------------------------------------------------------------------
 Thank you for your answer.

**Comment by darioizzo** [comment]
most likely your snopt7 dll is missing some symbols.

**Comment by darioizzo** [comment]
Will close this as its a snopt7 compilation issue. pykep pygmo work and are tested with the official snopt 7 libraries
