### ISSUE TITLE
Cannot run PyKep on MacOS High Sierra

### ISSUE THREAD

**Issue by jschach2020** [esa/pykep#87]
Computer Info: Macbook Pro
OS: MacOS High Sierra (10.13.5)

I am using a miniconda3 environment with pygmo2 and Python 3.7.1, installed directly through conda, following the installation instructions. 

When I try to install pykep for Unix based systems, I had a lot of trouble building it as there seemed to be linking issues with boost. I changed some things in the make file options, which can be seen in the below images, to try to link to the right python environment as well the boost python library included in miniconda3. 
<img width="955" alt="screen shot 2019-02-13 at 2 23 36 pm" src="https://user-images.githubusercontent.com/37714847/52737932-83d93f80-2f9b-11e9-9029-bf01b1ffcf1a.png">
<img width="954" alt="screen shot 2019-02-13 at 2 23 58 pm" src="https://user-images.githubusercontent.com/37714847/52737942-8d62a780-2f9b-11e9-99a3-0284a62a43fd.png">

This configuration allowed me to build and install everything without errors (which was a miracle for me as it took me a couple days to not get a "Boost::python37-NOTFOUND" error. 

When I import pykep into a python session, I don't get any errors. However, if I run the example script:
`import pykep as kp`
`pk.examples.run_example1(impulses = 3)`
I get this error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pykep' has no attribute 'examples'`

My friends, who also all have similar builds with MacOS are experiencing the same issue. Any advice for getting everything up and running smoothly?

**Comment by darioizzo** [comment]
Both unix and osx are building without problems, see our virtual machines in appveyor, travis and circle CI.

I see a few things that you are doing wrong.
1) You have installed some boost in /usr/local/lib (I guess homebrew?, does not matter, you have to use all the boost libraries installed in miniconda if you go for a miniconda build). I see you select a miniconda boost python, which is good, but allibraries have to be the ones of miniconda. So also serialization etc...
2) its `import pykep as pk` not `import pykep as kp`

Open up a python (or ipython session) and type:
```
from pykep import __version__ as ver
from pykep import __extensions__ as ext
print(ver)
print(ext)
```

what is your output?

**Comment by jschach2020** [comment]
Hey Dario,
Thanks for getting back to me! The example code i placed in my original was a typo, but I had it correct in the script that caused me to post this issue.

I see what you mean about linking to the miniconda3 boost libraries but am unsure of how exactly to link them. I've been working with this issue for quite some time and am not sure where to find the correct libraries for all boost related things in the following image of my ccmake interface. 
<img width="618" alt="screen shot 2019-02-13 at 5 20 59 pm" src="https://user-images.githubusercontent.com/37714847/52748320-3f0dd280-2fb4-11e9-9108-b804353f1bdd.png">

Do you by any chance know what libraries within miniconda3 i should be linking to? 

Unfortunately the version/extension commands did not work, this is the output:
<img width="572" alt="screen shot 2019-02-13 at 5 26 36 pm" src="https://user-images.githubusercontent.com/37714847/52748469-957b1100-2fb4-11e9-9a3b-fc2a570e25ac.png">

Please let me know if you have any other ideas! 

On a side note, we are gearing up to attempt GTOC X :) and have been quite inspired by your projects, keep up the awesome work!

**Comment by darioizzo** [comment]
In the same folder where you have the minoconda boost library ```libboost_python37.dylib``` you should have all the other boost libraries. link to those.

1) Do you install pykep? As in ```make install```?
2) If so whats the output of that make install command?
3) From what path do you start python?

**Comment by jschach2020** [comment]
Python path:
<img width="660" alt="screen shot 2019-02-13 at 5 46 48 pm" src="https://user-images.githubusercontent.com/37714847/52749506-60bc8900-2fb7-11e9-8734-b07d7066b947.png">


So the miniconda boost library thing is where I'm getting a bit confused because this is what is in that directory: (not much)
<img width="1136" alt="screen shot 2019-02-13 at 5 42 00 pm" src="https://user-images.githubusercontent.com/37714847/52749295-b93f5680-2fb6-11e9-903d-1b7bab18c047.png">

This is the output of the `make install` command as of now with the current cmake file configuration. When I ran it before, with the original configuration in my first comment, I got it to make and install without any errors. 
**Terminal Output:**

(base) Justins-MacBook-Pro-5:~ justinschachter$ cd pykep/build
(base) Justins-MacBook-Pro-5:build justinschachter$ make install
-- System name: Darwin
-- The C++ compiler ID is: AppleClang
-- YACMA autodetected C++ flags: -ftemplate-depth=1024;-fvisibility-inlines-hidden;-fvisibility=hidden
-- YACMA autodetected C++ debug flags: -Wshadow;-Werror;-Wall;-Wextra;-Wnon-virtual-dtor;-Wconversion;-Wdeprecated;-pedantic-errors;-Wdisabled-optimization;-ftemplate-backtrace-limit=0;-fstack-protector-all;-Wodr;-Wshift-negative-value
-- Clang compiler on OSX detected, setting the standard library to 'libc++'.
-- Python modules require linking to the Python library.
-- Python interpreter: /Users/justinschachter/miniconda3/bin/python
-- Python interpreter version: 3.7.1
-- Python libraries: /Users/justinschachter/miniconda3/lib/libpython3.7m.dylib
-- Python include dir: /Users/justinschachter/miniconda3/include/python3.7m
-- OS X platform detected.
-- Output extension for compiled modules will be '.so'.
-- Python modules install path: lib/python3.7/site-packages
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.13/Modules/FindBoost.cmake:1357 (file):
  file STRINGS file
  "/Users/justinschachter/miniconda3/pkgs/include/boost/version.hpp" cannot
  be read.
Call Stack (most recent call first):
  cmake_modules/PykepFindBoost.cmake:3 (find_package)
  CMakeLists.txt:88 (include)


CMake Error at /Applications/CMake.app/Contents/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 0.0.0

  Boost include path: /Users/justinschachter/miniconda3/pkgs/include

  Detected version of Boost is too old.  Requested version was 1.55 (or
  newer).
Call Stack (most recent call first):
  cmake_modules/PykepFindBoost.cmake:3 (find_package)
  CMakeLists.txt:88 (include)


-- Required Boost libraries: date_time;serialization;python3
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.13/Modules/FindBoost.cmake:1357 (file):
  file STRINGS file
  "/Users/justinschachter/miniconda3/pkgs/include/boost/version.hpp" cannot
  be read.
Call Stack (most recent call first):
  cmake_modules/PykepFindBoost.cmake:20 (find_package)
  CMakeLists.txt:88 (include)


CMake Error at /Applications/CMake.app/Contents/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 0.0.0

  Boost include path: /Users/justinschachter/miniconda3/pkgs/include

  Detected version of Boost is too old.  Requested version was 1.55 (or
  newer).
Call Stack (most recent call first):
  cmake_modules/PykepFindBoost.cmake:20 (find_package)
  CMakeLists.txt:88 (include)


CMake Error at cmake_modules/PykepFindBoost.cmake:22 (message):
  Not all requested Boost components were found, exiting.
Call Stack (most recent call first):
  CMakeLists.txt:88 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/justinschachter/pykep/build/CMakeFiles/CMakeOutput.log".
See also "/Users/justinschachter/pykep/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1
(base) Justins-MacBook-Pro-5:build justinschachter$

**Comment by darioizzo** [comment]
You probably have not installed the boost package from conda. Also do not use the directory PKG, only the lib directory of your conda environment.

Also it seems you are not using an environment in conda but the root conda installation that also is not good practice. I suggest you to follow some online tutorial or read docs on conda if you want to use it correctly.

Good luck. Will close this as it's not pykep related.
