### ISSUE TITLE
pip install pykep on Windows 10 64bit

### ISSUE THREAD

**Issue by perezedgar** [esa/pykep#95]
Hello, I am trying to install pykep using pip in Anaconda Prompt but it seems there is an issue because I have the following error:

> Collecting pykep
>    ERROR: Could not find a version that satisfies the requirement pykep (from versions: none)
ERROR: No matching distribution found for pykep

Best regards,

Edgar

**Comment by danlub** [comment]
I can reproduce
Windows 64bits, python 3.7

My guess is that there is no pykep wheel for Python 3.7 and Windows, as can be seen in PyPI

**Comment by perezedgar** [comment]
Hello thanks for your answer. I have created a new environment in Anaconda with python 3.6 which solves the problem

Best regards,

Edgar

**Comment by sork-dev** [comment]
Is it expected to release at any time a built version for Windows and Python 3.7 that can be easily installed through _conda_ or _pip_? 
From the user point of view, it would be highly appreciated, as having to build and install the _boost_ libraries just for compiling this package, its a bit inconvenient.

**Comment by darioizzo** [comment]
New release with conda win packages coming up (py38 available in conda)
