### ISSUE TITLE
pip install pykep is not working on macOS

### ISSUE THREAD

**Issue by vidhanarya** [esa/pykep#97]
We are using pykep for one of our projects, but users on macOS are experiencing a problem with the installation of pykep using pip. Below are the screenshots of the errors
<img width="1676" alt="Screenshot 2019-05-31 at 4 24 00 AM" src="https://user-images.githubusercontent.com/28908101/58670233-f3f9ae80-835b-11e9-99f4-0159cf8e2c26.png">
This is causing build failure on sphinx docs build of our project as shown below
<img width="1676" alt="Screenshot 2019-05-28 at 8 55 38 AM" src="https://user-images.githubusercontent.com/28908101/58670288-1c81a880-835c-11e9-9c5d-edd288d14ab3.png">

macOS version: 10.14.5

**Comment by darioizzo** [comment]
pykep is not available through pip for osx.
