### ISSUE TITLE
Can't import pykep on mac osx

### ISSUE THREAD

**Issue by jshan432** [esa/pykep#98]
I followed all installation instructions and successfully built pykep with the native python 2.7 on my machine, which runs MacOs Mojave.

![image](https://user-images.githubusercontent.com/52724974/60932279-439c9580-a28b-11e9-993c-03dad788c5f8.png)

When I try to import the pykep module I get the following error regarding the core module. Am I trying to import from the correct directory?

![image](https://user-images.githubusercontent.com/52724974/60932283-4eefc100-a28b-11e9-890e-37e02d5e72e4.png)

I downloaded boost with brew, and I've tried with brew python3 using the 

cmake ../ -DBUILD_PYKEP="ON"  -DPYTHON_EXECUTABLE="/usr/bin/python3.7m"

command, but cmake throws an error saying it can't find the python include directory. 

![image](https://user-images.githubusercontent.com/52724974/60932391-d3dada80-a28b-11e9-9ad2-9f17a8789987.png)

I'm very new to using python/building with cmake, so any feedback you can give is much appreciated.

Thanks, 

Jackson

**Comment by darioizzo** [comment]
start python from outside the pyked directory.

**Comment by jshan432** [comment]
Hi Dario, 

Thanks for your quick response. Now that I've gotten into it, I think I would rather use pykep with python 3.7 given the upcoming deprecation of python 2.7. Do you have any tips for my issues building with python 3.7? 

Thanks again, 

Jackson
