### ISSUE TITLE
Github.io documentation detail wrong for sims_flanagan leg

### ISSUE THREAD

**Issue by Badidzetai** [esa/pykep#99]
Hello everyone, 

[The pykep documentation for sims_flanagan leg](https://esa.github.io/pykep/documentation/simsflanagan.html#pykep.sims_flanagan.leg) mentions the high_fidelity as a method, but try to use the example 
```
l.high_fidelity(True)
```
results in error "Boolean is not callable", while using
```
l.high_fidelity = True
```
works. This suggests from the Python point of view, it is indeed an attribute and is to be manipulated like one.

Is there a misunderstanding on my side, or is it a mistake in the documentation ? I'll do the PR to correct the docs, if so.

Best,
B.

**Comment by darioizzo** [comment]
Thanks your PR has been merged!!
